const list = (names: readonly string[]) =>
  names.length <= 1 ? (names[0] ?? "") : `${names.slice(0, -1).join(", ")} and ${names.at(-1)}`;

export const liveClaimCopy = {
  metaTitle: "Claim your items",
  you: "You",
  back: "Items",
  title: { manager: "Who had what?", other: (payer: string, place: string) => `${payer}'s bill at ${place}` },
  body: {
    manager: "Send the link. Everyone taps their items; shared ones split automatically.",
    guest: "Tap what you had. No account needed.",
    member: "Tap what you had. Shared items split automatically.",
  },
  status: { ready: "Ready", claiming: "Claiming" },
  share: {
    copy: "Copy link",
    copied: "Copied",
    copiedToast: "Link copied. Go round them up.",
    share: "Share",
    shareText: (place: string) => `Tap what you had at ${place} on Bruno`,
  },
  presence: {
    alone: "Just you so far",
    here: (names: readonly string[]) => `${list(names)} are here`,
    label: "People here now",
  },
  identity: { as: "Claiming as", notYou: "Not you?" },
  outsider: {
    hint: (group: string) => `Tapping an item adds you to ${group}`,
    joined: (group: string) => `You’re in ${group}`,
  },
  live: {
    joined: (name: string) => `${name} joined. Hi ${name}.`,
    grabbed: (name: string, item: string) => `${name} grabbed the ${item}.`,
  },
  receipt: {
    paidBy: (when: string, payer: string) => `${when} · paid by ${payer}`,
    tapHint: "Tap if this was yours",
    each: (amount: string) => `${amount} each`,
    extras: (discounted: boolean) => (discounted ? "Tax, tip and discount" : "Tax and tip"),
    extrasShare: "Your share of it",
    progress: (done: number, all: number) => `${done} of ${all} claimed`,
  },
  unclaimed: {
    title: (n: number, total: string) => `${n} unclaimed · ${total}`,
    waiting: (names: readonly string[]) =>
      `${list(names)} ${names.length === 1 ? "hasn’t" : "haven’t"} tapped anything yet. Nudge them, or split what’s left evenly.`,
    allIn: "Everyone with an account is in. Split what’s left, or wait for the guests.",
    splitRest: "Split the rest",
  },
  remind: {
    labels: ["Remind", "Nudge again", "Final nudge", "Nudged"] as const,
    sent: (names: readonly string[]) => `Sent ${list(names)} a polite nudge.`,
    again: (names: readonly string[]) => `${list(names)} ${names.length === 1 ? "has" : "have"} been nudged. Firmly this time.`,
    final: "Dramatic nudge sent. They’ll feel it.",
    enough: "Three’s plenty. Give them a bit.",
    nobody: "Everyone with an account has already claimed.",
  },
  editor: { title: "Need percentages or fixed amounts?", body: "Open the split editor." },
  footer: {
    share: "Your share",
    finish: "Finish bill",
    finishAnyway: "Finish anyway",
    mine: "That’s mine",
    done: "Done",
    youreIn: "You’re in",
    waitingTitle: (payer: string) => `Waiting for ${payer} to finish the bill`,
    waitingBody: "You can still change your items until then.",
    finished: (title: string) => `${title} is done. Balances are updated.`,
    confirmed: (payer: string) => `You’re in. ${payer} will finish the bill.`,
    joined: (group: string) => `You joined ${group}.`,
    allClaimed: "Every item has a home. Nice work.",
  },
  who: {
    title: "Who are you?",
    body: (group: string) => `Pick yourself so everyone knows what you had. You’ll join ${group} as a guest.`,
    someoneElse: "Someone else",
    nameLabel: "Your name",
    placeholder: { others: "Type your name", first: "First name is fine" },
    join: "That’s me",
    account: "Have an account?",
    signIn: "Sign in",
    guestsLabel: "Guests in this group",
  },
  finished: {
    title: (place: string) => `${place} is all sorted`,
    body: (payer: string) => `${payer} finished the bill. Balances are up to date.`,
    meta: (group: string, payer: string, when: string) => `${group} · paid by ${payer} · ${when}`,
    yourShare: "Your share",
    total: "Bill total",
    nothing: "You didn’t claim anything, so nothing from this bill is on you.",
    spotTitle: (name: string) => `Your spot is saved as ${name}`,
    spotBody: (payer: string) => `Get Bruno to see what you owe ${payer} and settle up in a tap.`,
    nextTitle: "Split the next one with Bruno",
    nextBody: "Add the bill, send a link, done.",
    getBruno: "Get Bruno",
    haveAccount: "I have an account",
    openGroup: (group: string) => `Open ${group}`,
  },
  dead: {
    title: "This link isn’t working",
    body: "The bill may have been deleted. Ask whoever sent it for a new link.",
    home: "Go to Bruno",
  },
} as const;
