export const homeCopy = {
  tabs: {
    overview: "Overview",
    subscriptions: "Subscriptions",
    insights: "Insights",
    settings: "Settings",
  },
  overview: {
    perMonth: "a month",
    nextSevenDays: "Next seven days",
    nothingDue: "Nothing due this week.",
    whereItGoes: "Where it goes",
    insights: "Insights",
    closingOne: "1 subscription.",
    closingMany: "{count} subscriptions.",
    closingPaused: "{count} paused.",
    closingCancelled: "{count} cancelled.",
    emptyBody: "Nothing to track yet.\nAdd the first thing you pay for.",
    emptyAction: "Add a subscription",
  },
  insights: {
    title: "Insights",
    byCategory: "Where it goes",
    byMonth: "Next twelve months",
    average: "average",
    perYear: "Per year",
    active: "Active",
    shareLine: "{category} is {share}% of it.",
    saveLine: "Dropping {name} would save {amount} a year.",
    emptyBody: "Nothing to measure yet.\nAdd the first thing you pay for.",
    emptyAction: "Add a subscription",
  },
  settings: {
    title: "Settings",
    notifications: "Notifications",
    renewalReminders: "Renewal reminders",
    trialReminders: "Trial reminders",
    renewsToday: "Renews today",
    monthlyDigest: "Monthly digest",
    remindMe: "Remind me",
    leadDays: { "1": "1 day before", "3": "3 days before", "7": "1 week before" },
    account: "Account",
    email: "Email",
    signOut: "Sign out",
    deleteAccount: "Delete account",
    deleteTitle: "Delete your account?",
    deleteMessage:
      "Every subscription you have added will be erased. This cannot be undone.",
    deleteCancel: "Keep account",
    deleteConfirm: "Delete",
  },
} as const;
