export const homeCopy = {
  tabs: {
    overview: "Overview",
    subscriptions: "Subscriptions",
    insights: "Insights",
    settings: "Settings",
  },
  overview: {
    thisMonth: "This month",
    perMonthOne: "a month · 1 subscription",
    perMonthMany: "a month · {count} subscriptions",
    add: "Add subscription",
    insights: "Insights",
    upNext: "Up next",
    nothingDue: "Nothing due",
    nothingDueCaption: "No charges coming up",
    stillToCome: "Still to come",
    chargesOne: "1 charge by {date}",
    chargesMany: "{count} charges by {date}",
    seeAll: "See all",
    nothingThisWeek: "Nothing due this week.",
    active: "Active",
    trials: "On trial",
    paused: "Paused",
    cancelled: "Cancelled",
    aYear: "A year",
    emptyTitle: "No subscriptions yet",
    emptyBody: "Add the first one you pay for.",
    emptyAction: "Add subscription",
    errorTitle: "Couldn't load your list",
  },
  insights: {
    title: "Insights",
    yearEyebrow: "A year",
    perMonthCaption: "{monthly} a month",
    months: "Months",
    categories: "Categories",
    chart: "Monthly totals for the next 12 months",
    average: "Average month",
    highest: "Highest",
    lowest: "Lowest",
    categoryCaptionOne: "{share}% · 1 subscription",
    categoryCaptionMany: "{share}% · {count} subscriptions",
    facts: "Good to know",
    priciest: "Priciest",
    wouldSave: "Dropping it saves",
    perYear: "a year",
    emptyTitle: "Nothing to show yet",
    emptyBody: "Add a subscription and the numbers show up here.",
    emptyAction: "Add subscription",
    errorTitle: "Couldn't load your numbers",
  },
  settings: {
    title: "Settings",
    reminders: "Reminders",
    delivery: "Delivery",
    schedule: "Schedule",
    push: "Push notifications",
    emailChannel: "Email",
    renewalReminders: "Renewal reminders",
    trialReminders: "Trial reminders",
    renewsToday: "Renews today",
    monthlyDigest: "Monthly digest",
    remindMe: "Remind me",
    leadDays: { "1": "1 day before", "3": "3 days before", "7": "1 week before" },
    frequency: "Frequency",
    frequencyOptions: {
      event: "Only when due",
      daily: "Once a day",
      twice: "Twice a day",
    },
    time: "Time",
    secondTime: "Second time",
    loadErrorTitle: "Couldn't load your settings",
    retry: "Try again",
    appearance: "Appearance",
    theme: "Theme",
    appearanceOptions: { system: "System", light: "Light", dark: "Dark" },
    account: "Account",
    currency: "Currency",
    email: "Email",
    signOut: "Sign out",
    deleteAccount: "Delete account",
    deleteTitle: "Delete your account?",
    deleteMessage:
      "Every subscription you have added will be erased. This cannot be undone.",
    deleteCancel: "Keep account",
    deleteConfirm: "Delete",
  },
} as const;
