export const homeCopy = {
  tabs: {
    overview: "Overview",
    subscriptions: "Subscriptions",
    insights: "Insights",
    settings: "Settings",
  },
  overview: {
    thisMonth: "This month",
    perMonthOne: "a month · 1 subscription",
    perMonthMany: "a month · {count} subscriptions",
    add: "Add subscription",
    insights: "Insights",
    upNext: "Up next",
    nothingDue: "Nothing due",
    nothingDueCaption: "No charges coming up",
    stillToCome: "Still to come",
    chargesOne: "1 more by {date}",
    chargesMany: "{count} more by {date}",
    seeAll: "See all",
    nothingThisWeek: "Nothing due this week.",
    active: "Active",
    trials: "On trial",
    paused: "Paused",
    cancelled: "Cancelled",
    aYear: "A year",
    invite: {
      icon: "plus",
      title: "Every subscription,\none calm list",
      body: "Add what you pay for and Bruno does the remembering.",
      benefits: [
        {
          icon: "bell",
          title: "A nudge before every charge",
          caption: "1, 3 or 7 days ahead, your call",
        },
        {
          icon: "sum",
          title: "Your real monthly total",
          caption: "Yearly plans included, no maths needed",
        },
        {
          icon: "calendar",
          title: "Every renewal in one place",
          caption: "Sorted by whatever's next",
        },
      ],
      action: "Add your first subscription",
    },
    errorTitle: "Couldn't load your list",
  },
  insights: {
    title: "Insights",
    yearEyebrow: "A year",
    perMonthCaption: "{monthly} a month",
    months: "Months",
    categories: "Categories",
    chart: "Monthly totals for the next 12 months",
    average: "Average month",
    highest: "Highest",
    lowest: "Lowest",
    categoryCaptionOne: "{share}% · 1 subscription",
    categoryCaptionMany: "{share}% · {count} subscriptions",
    facts: "Good to know",
    priciest: "Priciest",
    wouldSave: "Dropping it saves",
    perYear: "a year",
    invite: {
      icon: "chart.bar.xaxis",
      title: "Numbers need\nsubscriptions",
      body: "Add a couple and Insights shows where the money really goes.",
      benefits: [
        {
          icon: "chart.bar",
          title: "Your year at a glance",
          caption: "Month by month, the next 12 months",
        },
        {
          icon: "chart.pie",
          title: "Where it all goes",
          caption: "Split by category",
        },
        {
          icon: "lightbulb",
          title: "What you could keep",
          caption: "Your priciest one, in the spotlight",
        },
      ],
      action: "Add a subscription",
    },
    errorTitle: "Couldn't load your numbers",
  },
  settings: {
    title: "Settings",
    reminders: "Reminders",
    delivery: "Delivery",
    schedule: "Schedule",
    push: "Push notifications",
    emailChannel: "Email",
    renewalReminders: "Renewal reminders",
    trialReminders: "Trial reminders",
    renewsToday: "Renews today",
    monthlyDigest: "Monthly digest",
    remindMe: "Remind me",
    leadDays: { "1": "1 day before", "3": "3 days before", "7": "1 week before" },
    frequency: "Frequency",
    frequencyOptions: {
      event: "Only when due",
      daily: "Once a day",
      twice: "Twice a day",
    },
    time: "Time",
    secondTime: "Second time",
    loadErrorTitle: "Couldn't load your settings",
    retry: "Try again",
    appearance: "Appearance",
    theme: "Theme",
    appearanceOptions: { system: "System", light: "Light", dark: "Dark" },
    account: "Account",
    currency: "Currency",
    email: "Email",
    signOut: "Sign out",
    deleteAccount: "Delete account",
    deleteTitle: "Delete your account?",
    deleteMessage:
      "Every subscription you have added will be erased. This cannot be undone.",
    deleteCancel: "Keep account",
    deleteConfirm: "Delete",
  },
} as const;
