export const subscriptionsCopy = {
  list: {
    title: "Subscriptions",
    add: "Add subscription",
    loading: "Loading your subscriptions.",
    retry: "Try again",
    invite: {
      icon: "creditcard",
      title: "Your list\nstarts here",
      body: "Streaming, the gym, that app you forgot about. Add them once and they stay sorted.",
      benefits: [
        {
          icon: "magnifyingglass",
          title: "Logos found for you",
          caption: "Type a name, pick the match",
        },
        {
          icon: "arrow.up.arrow.down",
          title: "Sorted your way",
          caption: "By next renewal, cost or name",
        },
        {
          icon: "pause.circle",
          title: "Pause or cancel anytime",
          caption: "Keep the history, drop the charge",
        },
      ],
      action: "Add your first subscription",
    },
    errorTitle: "Couldn't load your list",
    filterEmpty: "No {filter} subscriptions",
    showAll: "Show all",
    activeCaption: "{amount} a month across {count}",
    trialNote: "Trial",
    yearNote: "{amount} a year",
    groupPaused: "Paused",
    groupCancelled: "Cancelled",
    filters: {
      all: "All",
      monthly: "Monthly",
      yearly: "Yearly",
      paused: "Paused",
    },
    searchPlaceholder: "Search",
    sortLabel: "Sort",
    sorts: {
      renewal: "Next renewal",
      monthly: "Monthly cost",
      name: "Name",
    },
    searchEmpty: "Nothing called “{query}”",
    searchEmptyBody: "Try a name, a category or a card label.",
    clearSearch: "Clear search",
  },
  form: {
    title: "New subscription",
    cancel: "Cancel",
    confirm: "Add",
    name: "Name",
    namePlaceholder: "Netflix, Spotify, the gym…",
    suggestions: "Suggestions",
    nameHint: "Pick a match below to add its logo. Your own name works too.",
    searching: "Looking for a logo…",
    noMatches: "No logo found for that name. You can still add it.",
    logoFrom: "Logo from {domain}",
    removeLogo: "Remove logo",
    amount: "Amount",
    amountPlaceholder: "0.00",
    every: "Every",
    firstPayment: "First payment",
    category: "Category",
    categoryNone: "None",
    more: "Trial, payment method, notes",
    trial: "Free trial",
    trialHint: "Free until the first payment. The amount is what it costs after.",
    paymentMethod: "Payment method",
    paymentMethodPlaceholder: "Amex 1009",
    paymentMethodHint: "A label only. Never a full card number.",
    notes: "Notes",
    notesPlaceholder: "Family plan",
    save: "Add subscription",
  },
  detail: {
    back: "Back",
    edit: "Edit",
    renews: "Renews {when}",
    trialEnds: "Free trial ends {when}",
    details: "Details",
    actions: "What you can do",
    trialUntil: "Free until",
    paused: "Paused",
    cancelled: "Cancelled",
    sinceLabel: "Since",
    repeats: "Repeats",
    nextPayment: "Next payment",
    category: "Category",
    paymentMethod: "Payment method",
    notes: "Notes",
    trial: "Free trial",
    pause: "Pause",
    pauseTitle: "Pause this subscription?",
    pauseMessage:
      "Bruno stops counting it until you resume. The plan with the service is not affected.",
    pauseConfirm: "Pause",
    resume: "Resume",
    resumeTitle: "Resume this subscription?",
    resumeMessage: "It picks up on its original schedule.",
    resumeConfirm: "Resume",
    cancel: "Cancel",
    cancelTitle: "Mark as cancelled?",
    cancelMessage:
      "Bruno keeps the record but stops counting it. This does not cancel the plan with the service.",
    cancelConfirm: "Mark cancelled",
    reactivate: "Reactivate",
    reactivateTitle: "Reactivate this subscription?",
    reactivateMessage: "It picks up on its original schedule.",
    reactivateConfirm: "Reactivate",
    keep: "Not now",
    delete: "Delete subscription",
    deleteTitle: "Delete this subscription?",
    deleteMessage:
      "This only removes it from Bruno. It does not cancel the plan with the service.",
    deleteConfirm: "Delete",
    deleteCancel: "Cancel",
    notFoundTitle: "This one's gone",
    notFoundBody: "It may have been deleted on another device.",
    notFoundAction: "Back",
    loading: "Loading",
  },
  edit: {
    title: "Edit subscription",
    confirm: "Save",
    save: "Save changes",
    nextPayment: "Next payment",
    trialHint: "Free until the next payment. The amount is what it costs after.",
    notFoundTitle: "This one's gone",
    notFoundBody: "It may have been deleted on another device.",
    notFoundAction: "Close",
  },
  relative: {
    today: "today",
    tomorrow: "tomorrow",
    inDays: "in {days} days",
  },
  relativeTitle: {
    today: "Today",
    tomorrow: "Tomorrow",
    inDays: "In {days} days",
  },
  logos: {
    credit: "Logos provided by Logo.dev",
  },
  cycleAdverb: { day: "daily", week: "weekly", month: "monthly", year: "yearly" },
  per: { day: "a day", week: "a week", month: "a month", year: "a year" },
  every: "every {cycle}",
  cycleUnits: {
    one: { day: "Day", week: "Week", month: "Month", year: "Year" },
    many: { day: "days", week: "weeks", month: "months", year: "years" },
  },
  cycles: {
    weekly: "Week",
    monthly: "Month",
    quarterly: "3 months",
    yearly: "Year",
  },
  categories: {
    entertainment: "Entertainment",
    music: "Music",
    productivity: "Productivity",
    cloud_storage: "Cloud & Storage",
    news_reading: "News & Reading",
    health_fitness: "Health & Fitness",
    gaming: "Gaming",
    utilities_bills: "Utilities & Bills",
    education: "Education",
    other: "Other",
  },
  errors: {
    alertTitle: "Something went wrong",
    dismiss: "OK",
    network: "Check your connection and try again.",
    session: "Your session has expired. Sign in again.",
    invalid: "Some of those details do not look right.",
    limitReached: "You have reached the limit of 500 subscriptions.",
    generic: "We could not finish that. Try again in a moment.",
    amountInvalid: "Enter an amount like 9.99.",
    paymentMethodDigits: "Use a short label, not a card number.",
  },
} as const;
