export const subscriptionsCopy = {
  list: {
    title: "Subscriptions.",
    add: "Add",
    loading: "Loading your subscriptions.",
    emptyBody: "Nothing here yet.\nAdd the first thing you pay for.",
    emptyAction: "Add a subscription",
    retry: "Try again",
    trialNote: "Trial ends",
    pausedNote: "Paused",
    cancelledNote: "Cancelled",
  },
  form: {
    title: "New subscription.",
    cancel: "Cancel",
    confirm: "Add",
    name: "Name",
    namePlaceholder: "Netflix",
    amount: "Amount",
    amountPlaceholder: "0.00",
    every: "Every",
    firstPayment: "First payment",
    category: "Category",
    categoryNone: "None",
    more: "Free trial, payment method, notes",
    trial: "Free trial",
    trialHint: "Free until the first payment. The amount is what it costs after.",
    paymentMethod: "Payment method",
    paymentMethodPlaceholder: "Amex 1009",
    paymentMethodHint: "A label only. Never a full card number.",
    notes: "Notes",
    notesPlaceholder: "Family plan",
    save: "Add subscription",
  },
  cycles: {
    weekly: "Week",
    monthly: "Month",
    quarterly: "3 months",
    yearly: "Year",
  },
  categories: {
    entertainment: "Entertainment",
    music: "Music",
    productivity: "Productivity",
    cloud_storage: "Cloud & Storage",
    news_reading: "News & Reading",
    health_fitness: "Health & Fitness",
    gaming: "Gaming",
    utilities_bills: "Utilities & Bills",
    education: "Education",
    other: "Other",
  },
  errors: {
    alertTitle: "Something went wrong",
    dismiss: "OK",
    network: "Check your connection and try again.",
    session: "Your session has expired. Sign in again.",
    invalid: "Some of those details do not look right.",
    limitReached: "You have reached the limit of 500 subscriptions.",
    generic: "We could not finish that. Try again in a moment.",
    amountInvalid: "Enter an amount like 9.99.",
    paymentMethodDigits: "Use a short label, not a card number.",
  },
} as const;
