import type { FractionDigits } from "./money";

export type Currency = {
  code: string;
  name: string;
  digits: FractionDigits;
};

export const currencies: readonly Currency[] = [
  { code: "AED", name: "UAE Dirham", digits: 2 },
  { code: "AFN", name: "Afghan Afghani", digits: 2 },
  { code: "ALL", name: "Albanian Lek", digits: 2 },
  { code: "AMD", name: "Armenian Dram", digits: 2 },
  { code: "AOA", name: "Angolan Kwanza", digits: 2 },
  { code: "ARS", name: "Argentine Peso", digits: 2 },
  { code: "AUD", name: "Australian Dollar", digits: 2 },
  { code: "AWG", name: "Aruban Florin", digits: 2 },
  { code: "AZN", name: "Azerbaijani Manat", digits: 2 },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", digits: 2 },
  { code: "BBD", name: "Barbadian Dollar", digits: 2 },
  { code: "BDT", name: "Bangladeshi Taka", digits: 2 },
  { code: "BHD", name: "Bahraini Dinar", digits: 3 },
  { code: "BIF", name: "Burundian Franc", digits: 0 },
  { code: "BMD", name: "Bermudan Dollar", digits: 2 },
  { code: "BND", name: "Brunei Dollar", digits: 2 },
  { code: "BOB", name: "Bolivian Boliviano", digits: 2 },
  { code: "BRL", name: "Brazilian Real", digits: 2 },
  { code: "BSD", name: "Bahamian Dollar", digits: 2 },
  { code: "BTN", name: "Bhutanese Ngultrum", digits: 2 },
  { code: "BWP", name: "Botswanan Pula", digits: 2 },
  { code: "BYN", name: "Belarusian Ruble", digits: 2 },
  { code: "BZD", name: "Belize Dollar", digits: 2 },
  { code: "CAD", name: "Canadian Dollar", digits: 2 },
  { code: "CDF", name: "Congolese Franc", digits: 2 },
  { code: "CHF", name: "Swiss Franc", digits: 2 },
  { code: "CLP", name: "Chilean Peso", digits: 0 },
  { code: "CNY", name: "Chinese Yuan", digits: 2 },
  { code: "COP", name: "Colombian Peso", digits: 2 },
  { code: "CRC", name: "Costa Rican Colón", digits: 2 },
  { code: "CUP", name: "Cuban Peso", digits: 2 },
  { code: "CVE", name: "Cape Verdean Escudo", digits: 2 },
  { code: "CZK", name: "Czech Koruna", digits: 2 },
  { code: "DJF", name: "Djiboutian Franc", digits: 0 },
  { code: "DKK", name: "Danish Krone", digits: 2 },
  { code: "DOP", name: "Dominican Peso", digits: 2 },
  { code: "DZD", name: "Algerian Dinar", digits: 2 },
  { code: "EGP", name: "Egyptian Pound", digits: 2 },
  { code: "ERN", name: "Eritrean Nakfa", digits: 2 },
  { code: "ETB", name: "Ethiopian Birr", digits: 2 },
  { code: "EUR", name: "Euro", digits: 2 },
  { code: "FJD", name: "Fijian Dollar", digits: 2 },
  { code: "FKP", name: "Falkland Islands Pound", digits: 2 },
  { code: "GBP", name: "British Pound", digits: 2 },
  { code: "GEL", name: "Georgian Lari", digits: 2 },
  { code: "GHS", name: "Ghanaian Cedi", digits: 2 },
  { code: "GIP", name: "Gibraltar Pound", digits: 2 },
  { code: "GMD", name: "Gambian Dalasi", digits: 2 },
  { code: "GNF", name: "Guinean Franc", digits: 0 },
  { code: "GTQ", name: "Guatemalan Quetzal", digits: 2 },
  { code: "GYD", name: "Guyanaese Dollar", digits: 2 },
  { code: "HKD", name: "Hong Kong Dollar", digits: 2 },
  { code: "HNL", name: "Honduran Lempira", digits: 2 },
  { code: "HTG", name: "Haitian Gourde", digits: 2 },
  { code: "HUF", name: "Hungarian Forint", digits: 2 },
  { code: "IDR", name: "Indonesian Rupiah", digits: 2 },
  { code: "ILS", name: "Israeli New Shekel", digits: 2 },
  { code: "INR", name: "Indian Rupee", digits: 2 },
  { code: "IQD", name: "Iraqi Dinar", digits: 3 },
  { code: "IRR", name: "Iranian Rial", digits: 2 },
  { code: "ISK", name: "Icelandic Króna", digits: 0 },
  { code: "JMD", name: "Jamaican Dollar", digits: 2 },
  { code: "JOD", name: "Jordanian Dinar", digits: 3 },
  { code: "JPY", name: "Japanese Yen", digits: 0 },
  { code: "KES", name: "Kenyan Shilling", digits: 2 },
  { code: "KGS", name: "Kyrgystani Som", digits: 2 },
  { code: "KHR", name: "Cambodian Riel", digits: 2 },
  { code: "KMF", name: "Comorian Franc", digits: 0 },
  { code: "KPW", name: "North Korean Won", digits: 2 },
  { code: "KRW", name: "South Korean Won", digits: 0 },
  { code: "KWD", name: "Kuwaiti Dinar", digits: 3 },
  { code: "KYD", name: "Cayman Islands Dollar", digits: 2 },
  { code: "KZT", name: "Kazakhstani Tenge", digits: 2 },
  { code: "LAK", name: "Laotian Kip", digits: 2 },
  { code: "LBP", name: "Lebanese Pound", digits: 2 },
  { code: "LKR", name: "Sri Lankan Rupee", digits: 2 },
  { code: "LRD", name: "Liberian Dollar", digits: 2 },
  { code: "LSL", name: "Lesotho Loti", digits: 2 },
  { code: "LYD", name: "Libyan Dinar", digits: 3 },
  { code: "MAD", name: "Moroccan Dirham", digits: 2 },
  { code: "MDL", name: "Moldovan Leu", digits: 2 },
  { code: "MGA", name: "Malagasy Ariary", digits: 2 },
  { code: "MKD", name: "Macedonian Denar", digits: 2 },
  { code: "MMK", name: "Myanmar Kyat", digits: 2 },
  { code: "MNT", name: "Mongolian Tugrik", digits: 2 },
  { code: "MOP", name: "Macanese Pataca", digits: 2 },
  { code: "MRU", name: "Mauritanian Ouguiya", digits: 2 },
  { code: "MUR", name: "Mauritian Rupee", digits: 2 },
  { code: "MVR", name: "Maldivian Rufiyaa", digits: 2 },
  { code: "MWK", name: "Malawian Kwacha", digits: 2 },
  { code: "MXN", name: "Mexican Peso", digits: 2 },
  { code: "MYR", name: "Malaysian Ringgit", digits: 2 },
  { code: "MZN", name: "Mozambican Metical", digits: 2 },
  { code: "NAD", name: "Namibian Dollar", digits: 2 },
  { code: "NGN", name: "Nigerian Naira", digits: 2 },
  { code: "NIO", name: "Nicaraguan Córdoba", digits: 2 },
  { code: "NOK", name: "Norwegian Krone", digits: 2 },
  { code: "NPR", name: "Nepalese Rupee", digits: 2 },
  { code: "NZD", name: "New Zealand Dollar", digits: 2 },
  { code: "OMR", name: "Omani Rial", digits: 3 },
  { code: "PAB", name: "Panamanian Balboa", digits: 2 },
  { code: "PEN", name: "Peruvian Sol", digits: 2 },
  { code: "PGK", name: "Papua New Guinean Kina", digits: 2 },
  { code: "PHP", name: "Philippine Peso", digits: 2 },
  { code: "PKR", name: "Pakistani Rupee", digits: 2 },
  { code: "PLN", name: "Polish Złoty", digits: 2 },
  { code: "PYG", name: "Paraguayan Guarani", digits: 0 },
  { code: "QAR", name: "Qatari Riyal", digits: 2 },
  { code: "RON", name: "Romanian Leu", digits: 2 },
  { code: "RSD", name: "Serbian Dinar", digits: 2 },
  { code: "RUB", name: "Russian Ruble", digits: 2 },
  { code: "RWF", name: "Rwandan Franc", digits: 0 },
  { code: "SAR", name: "Saudi Riyal", digits: 2 },
  { code: "SBD", name: "Solomon Islands Dollar", digits: 2 },
  { code: "SCR", name: "Seychellois Rupee", digits: 2 },
  { code: "SDG", name: "Sudanese Pound", digits: 2 },
  { code: "SEK", name: "Swedish Krona", digits: 2 },
  { code: "SGD", name: "Singapore Dollar", digits: 2 },
  { code: "SHP", name: "St. Helena Pound", digits: 2 },
  { code: "SLE", name: "Sierra Leonean Leone", digits: 2 },
  { code: "SOS", name: "Somali Shilling", digits: 2 },
  { code: "SRD", name: "Surinamese Dollar", digits: 2 },
  { code: "SSP", name: "South Sudanese Pound", digits: 2 },
  { code: "STN", name: "São Tomé and Príncipe Dobra", digits: 2 },
  { code: "SYP", name: "Syrian Pound", digits: 2 },
  { code: "SZL", name: "Swazi Lilangeni", digits: 2 },
  { code: "THB", name: "Thai Baht", digits: 2 },
  { code: "TJS", name: "Tajikistani Somoni", digits: 2 },
  { code: "TMT", name: "Turkmenistani Manat", digits: 2 },
  { code: "TND", name: "Tunisian Dinar", digits: 3 },
  { code: "TOP", name: "Tongan Paʻanga", digits: 2 },
  { code: "TRY", name: "Turkish Lira", digits: 2 },
  { code: "TTD", name: "Trinidad and Tobago Dollar", digits: 2 },
  { code: "TWD", name: "New Taiwan Dollar", digits: 2 },
  { code: "TZS", name: "Tanzanian Shilling", digits: 2 },
  { code: "UAH", name: "Ukrainian Hryvnia", digits: 2 },
  { code: "UGX", name: "Ugandan Shilling", digits: 0 },
  { code: "USD", name: "US Dollar", digits: 2 },
  { code: "UYU", name: "Uruguayan Peso", digits: 2 },
  { code: "UZS", name: "Uzbekistani Som", digits: 2 },
  { code: "VES", name: "Venezuelan Bolívar", digits: 2 },
  { code: "VND", name: "Vietnamese Dong", digits: 0 },
  { code: "VUV", name: "Vanuatu Vatu", digits: 0 },
  { code: "WST", name: "Samoan Tala", digits: 2 },
  { code: "XAF", name: "Central African CFA Franc", digits: 0 },
  { code: "XCD", name: "East Caribbean Dollar", digits: 2 },
  { code: "XCG", name: "Caribbean Guilder", digits: 2 },
  { code: "XOF", name: "West African CFA Franc", digits: 0 },
  { code: "XPF", name: "CFP Franc", digits: 0 },
  { code: "YER", name: "Yemeni Rial", digits: 2 },
  { code: "ZAR", name: "South African Rand", digits: 2 },
  { code: "ZMW", name: "Zambian Kwacha", digits: 2 },
  { code: "ZWG", name: "Zimbabwean Gold", digits: 2 },
];

const byCode = new Map(currencies.map((currency) => [currency.code, currency]));

export function findCurrency(code: string): Currency | null {
  return byCode.get(code) ?? null;
}

export function isSupportedCurrency(code: string): boolean {
  return byCode.has(code);
}

export function currencyName(code: string): string {
  return byCode.get(code)?.name ?? code;
}

export function searchCurrencies(query: string): readonly Currency[] {
  const needle = query.trim().toLowerCase();
  if (needle.length === 0) {
    return currencies;
  }
  return currencies.filter(
    (currency) =>
      currency.code.toLowerCase().includes(needle) ||
      currency.name.toLowerCase().includes(needle),
  );
}
