export const GROUP_TABS = ["bills", "balances", "members"] as const;

export const GUEST_CLAIM_LINKS = true;
export type GroupTab = (typeof GROUP_TABS)[number];

export const groupDetailCopy = {
  metaTitle: "Group",
  youName: "You",
  back: "Groups",
  tabs: { bills: "Bills", balances: "Balances", members: "Members" },
  tabsLabel: "Group sections",
  inviteLink: "Invite link",
  copyLink: "Copy link",
  copied: "Copied",
  addBill: "Add a bill",
  settings: "Group settings",
  membersLine: (names: readonly string[], currency: string) => `${joinNames(names)} · ${currency}`,
  summary: {
    spent: "Group spent",
    share: "Your share",
    owed: "You're owed",
    owe: "You owe",
    square: "All square",
  },
  bills: { title: "No bills yet.", body: "Add the first one and Bruno will keep the running tab." },
  billList: {
    label: "Bills in this group",
    paidBy: (name: string) => `Paid by ${name}`,
    claiming: (claimed: number, items: number) => `${claimed} of ${items} claimed`,
  },
  balanceList: {
    label: "Balances",
    owes: (titles: readonly string[]) => (titles.length > 0 ? `owes · ${titles.join(", ")}` : "owes"),
    owed: (paid: number, involved: number) => `is owed · paid ${paid} of ${involved} ${involved === 1 ? "bill" : "bills"}`,
    square: "all square",
    settleTitle: "Smart settlement",
    settleBody: (n: number) => (n === 1 ? "One payment clears the whole group." : `${n} payments clear the whole group.`),
    payments: (n: number) => `${n} ${n === 1 ? "payment" : "payments"}`,
    pays: (from: string, to: string) => `${from} ${from === "You" ? "pay" : "pays"} ${to === "You" ? "you" : to}`,
    settleUp: "Settle up",
    pendingTitle: (name: string, amount: string) => `${name} says they paid you ${amount}`,
    pendingBody: "Confirm it landed and the balance clears.",
    pendingCta: "Confirm",
  },
  paymentList: {
    title: "Payments",
    label: "Recent payments",
    line: (from: string, to: string, amount: string) => `${from} paid ${to === "You" ? "you" : to} ${amount}`,
    caption: (method: string, day: string) => `${method} · ${day}`,
    status: { pending: "Pending", confirmed: "Confirmed", auto: (day: string) => `Confirms ${day}` },
    undo: "Undo",
    confirm: "Confirm",
    decline: "Didn't get it",
    undone: "Undone. No one saw a thing.",
    confirmed: "Confirmed. Balance updated.",
    declined: "Marked as not received.",
  },
  balances: { title: "Everyone's square.", body: "Balances show up here once there are bills." },
  members: {
    you: "(you)",
    admin: "Admin",
    member: "Member",
    joined: (date: string) => `joined ${date}`,
    guest: "Guest",
    addedBy: (name: string) => `added by ${name}`,
    addedByYou: "added by you",
    more: (name: string) => `Options for ${name}`,
    manage: (name: string) => `Manage ${name}`,
    add: "Add people",
    note: "Anyone with the link can join. Guests can be on bills before they join Bruno.",
  },
  addPeople: {
    title: (group: string) => `Add people to ${group}`,
    close: "Close",
    queryLabel: "Username or email",
    queryPlaceholder: "@priya or priya@email.com",
    find: "Find",
    helper: "They need a Bruno account. We only find exact matches.",
    looking: "Looking…",
    rateLimited: "That's a lot of lookups. Give it a minute and try again.",
    add: (group: string) => `Add to ${group}`,
    addBack: "Add back",
    added: "Added",
    already: (group: string) => `Already in ${group}`,
    justAdded: "Just added",
    guestTag: "guest",
    notFoundTitle: (query: string) => `No match for ${query}`,
    notFoundBody: "No Bruno account matches that. Invite them, or add them by name for now.",
    sendInvite: "Send them the invite link",
    inviteCopied: "Link copied",
    addByNameInstead: (name: string) => (name ? `Add ${name} by name instead` : "Add them by name instead"),
    notOnBruno: "Not on Bruno yet?",
    addByName: "Add them by name",
    backToLookup: "Username or email",
    shareLink: "Or share the invite link",
    copy: "Copy",
    nameLabel: "Their name",
    namePlaceholder: "e.g. Leo",
    buddyTitle: (name: string) => (name ? `${name}'s buddy` : "Their buddy"),
    buddyAuto: (shape: string) => `${shape}, picked for them. Tap to change.`,
    buddyPicked: (shape: string, tint: string) => `${shape} in ${tint}. Tap to change.`,
    changeBuddy: "Change their buddy",
    buddyLabel: "Buddy",
    colourLabel: "Colour",
    addGuest: (name: string) => (name ? `Add ${name}` : "Add them"),
    guestNote: "They'll show as a guest until they join Bruno. Their bills carry over when they do.",
  },
  guestSheet: {
    close: "Close",
    role: (addedBy: string) => `Guest · ${addedBy}`,
    owes: (amount: string) => `Owes ${amount}`,
    owed: (amount: string) => `Is owed ${amount}`,
    rename: "Rename",
    renameSub: "Only this group sees it",
    renameLabel: "Guest name",
    save: "Save",
    buddy: "Change buddy and colour",
    buddySub: (shape: string, tint: string) => `${shape} in ${tint}`,
    invite: "Send invite link",
    inviteCopied: "Invite link copied",
    inviteSub: (name: string) => `${name} joins Bruno and takes over this spot.`,
    remove: (group: string) => `Remove from ${group}`,
    removeSub: "Their settled bills stay in the history",
    removeLocked: "Not while they have an open balance",
    removeNotAllowed: "Only an admin or whoever added them can remove a guest",
    lockReason: (name: string) => `${name} has an open balance. Once that's settled you can remove them.`,
    settleUp: "Settle up",
    confirmRemove: (name: string, group: string) => `Remove ${name} from ${group}? Their settled bills stay in the history.`,
    confirmYes: (name: string) => `Remove ${name}`,
    keep: "Keep",
  },
  memberSheet: {
    makeAdmin: "Make admin",
    makeMember: "Remove admin",
    remove: "Remove from group",
    leave: "Leave group",
    confirmRemove: (name: string) => `Remove ${name}?`,
    confirmRemoveBody: "They'll lose access to this group. You can invite them again any time.",
    confirmLeave: "Leave this group?",
    confirmLeaveBody: "You'll need a new invite link to come back.",
    confirm: "Yes, do it",
    cancel: "Cancel",
  },
  settingsSheet: {
    title: "Group settings",
    description: "Change how the group looks. Everyone sees the same thing.",
    save: "Save changes",
    saved: "Group updated",
    reset: "Reset invite link",
    resetBody: "The current link stops working right away.",
    resetDone: "New invite link ready",
    delete: "Delete group",
    deleteBody: "This hides the group for everyone. Bills and history are kept.",
    deleteBlocked: "Everyone needs to be square before the group can be deleted.",
    confirm: "Yes, do it",
    cancel: "Cancel",
  },
} as const;

function joinNames(names: readonly string[]): string {
  if (names.length <= 1) return names[0] ?? "";
  return `${names.slice(0, -1).join(", ")} and ${names[names.length - 1]}`;
}
