export const emailCopy = {
  brand: "Bruno",
  footer: {
    reminders:
      "You're getting this because reminders are on in Bruno. Turn any of them off in Settings.",
    account: "Sent by Bruno because of activity on your account.",
  },
  code: {
    subject: "Your Bruno code",
    preview: "Your six-digit code",
    eyebrow: "Sign-in code",
    title: "Here's your code",
    expiry:
      "It works for ten minutes. Didn't ask for it? You can ignore this email.",
  },
  reset: {
    subject: "Reset your Bruno password",
    preview: "Your password reset code",
    eyebrow: "Password reset",
    title: "Reset your password",
    expiry: "It works for ten minutes. Didn't ask for it? Nothing has changed.",
  },
  alreadyRegistered: {
    subject: "You already have a Bruno account",
    preview: "No new account was created",
    eyebrow: "Account",
    title: "You already have an account",
    body: "Someone tried to sign up with this address. You already have an account, so nothing was created.",
    hint: "If that was you, open Bruno and sign in instead. Can't remember your password? Choose forgot password on the sign-in screen.",
  },
  passwordChanged: {
    subject: "Your Bruno password was changed",
    preview: "Every device was signed out",
    eyebrow: "Account",
    title: "Your password was changed",
    body: "Your password was changed just now, and every device has been signed out.",
    hint: "If that wasn't you, set a new password straight away.",
  },
  welcome: {
    subject: "Welcome to Bruno",
    preview: "Your wallet has a new guard dog.",
    eyebrow: "Welcome",
    title: "Your wallet has a new guard dog",
    body: "Your email is verified and your account is ready. Add the first thing you pay for and Bruno keeps an eye on the dates, the totals and the sneaky renewals.",
    hint: "We'll nudge you before anything charges. Open Bruno to add your first subscription.",
  },
  accountDeleted: {
    subject: "Your Bruno account is deleted",
    preview: "Everything has been erased",
    eyebrow: "Account",
    title: "Your account is deleted",
    body: "Your account and every subscription in it have been erased. There is nothing left to recover.",
    hint: "Thanks for giving Bruno a try.",
  },
  relative: { one: "tomorrow", three: "in three days", seven: "in a week" },
  today: "Today",
  trialChip: "Trial",
  renewal: {
    subject: "{name} wants {amount} {when}",
    preview: "{date}. Still using it?",
    eyebrow: "Renewal reminder",
    title: "{name} is back {when}",
    body: "{name} helps itself to {amount} {when}, on {date}.",
    wink: "Still using it? Carry on. If not, cancel before {date} and that's {yearly} a year back in your pocket.",
    renews: "Renews",
    every: "Every",
  },
  trial: {
    subject: "Your {name} free trial ends {when}",
    preview: "Then {amount} {per}.",
    eyebrow: "Trial ending",
    title: "The free ride with {name} is almost over",
    body: "The trial ends {when}, on {date}. After that, {name} starts charging {amount} {per}.",
    wink: "Loving it? You're all set, nothing to do. Just browsing? Cancel before {date} and it never costs a thing.",
    ends: "Trial ends",
    after: "Then",
  },
  renewsToday: {
    subject: "{name} is collecting {amount} today",
    preview: "Hopefully it's earning its keep.",
    eyebrow: "Renews today",
    title: "Payday for {name}",
    body: "{name} takes {amount} today. Hopefully it's earning its keep.",
    wink: "If it isn't, cancel now and this one is the last.",
  },
  batch: {
    subject: "{count} subscriptions are about to knock",
    preview: "{first} and {rest} more",
    eyebrow: "Coming up",
    title: "A few subscriptions are lining up",
    lead: "Here's who's heading for your wallet soon:",
    renewal: "Renews {when}",
    trial: "Trial ends {when}",
    renews_today: "Renews today",
    wink: "Keeping them all? Nothing to do. Outgrown one? Cancel it before its date.",
  },
  digest: {
    subject: "{month}: {total} heading out the door",
    subjectNone: "{month}: a quiet month",
    preview: "{count} due this month, {total} in all",
    eyebrow: "Your month",
    title: "{month} at a glance",
    titleNone: "A quiet month",
    chargesOne: "1 charge this month",
    chargesMany: "{count} charges this month",
    leadOne: "1 subscription is due this month, {total} in all.",
    leadMany: "{count} subscriptions are due this month, {total} in all.",
    leadNone: "Nothing renews this month. Your wallet says thanks.",
    more: "and {count} more",
    monthlyLabel: "A month",
    monthly: "Your monthly total is {monthly}.",
    topLabel: "Biggest share",
    top: "{category}, {amount} a month",
    wink: "That's the lot. Anything you don't use any more is money you can keep.",
  },
  per: { day: "a day", week: "a week", month: "a month", year: "a year" },
  every: "every {count} {unit}",
  units: { day: "days", week: "weeks", month: "months", year: "years" },
  cycleOne: { day: "Day", week: "Week", month: "Month", year: "Year" },
} as const;
