export const mail = {
  paper: "#FBFAF7",
  ink: "#1A1917",
  ink2: "#5F5D58",
  ink3: "#75736E",
  hair: "#E8E6E1",
  font: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
  width: "480px",
  bodyPadding: "32px 16px",
  containerPadding: "24px",
  wordmarkSize: "17px",
  bodySize: "15px",
  bodyLine: "22px",
  captionSize: "13px",
  captionLine: "18px",
  codeSize: "28px",
  codeTracking: "4px",
  rowPadding: "10px 0",
  gap: "16px",
} as const;
