export const authCopy = {
  signUp: {
    title: "Create your account.",
    body: "An email and a password. That is all we keep.",
    emailLabel: "Email",
    passwordLabel: "Password",
    passwordHint: "At least 8 characters, with one number.",
    show: "Show",
    hide: "Hide",
    primary: "Continue",
    secondary: "Already have an account? Sign in",
  },
  signIn: {
    title: "Welcome back.",
    body: "Sign in to your ledger.",
    emailLabel: "Email",
    passwordLabel: "Password",
    show: "Show",
    hide: "Hide",
    forgot: "Forgot password?",
    primary: "Sign in",
    secondary: "New here? Create an account",
  },
  unverified: {
    title: "Email not verified",
    messageLead: "Check your inbox for the six-digit code we sent to ",
    messageTail: ".",
    cancel: "Cancel",
    confirm: "Verify now",
  },
  reset: {
    title: "Reset your password.",
    body: "Choose a new password. We will email you a code to confirm it.",
    emailLabel: "Email",
    passwordLabel: "New password",
    passwordHint: "At least 8 characters, with one number.",
    show: "Show",
    hide: "Hide",
    primary: "Send code",
    secondary: "Back to sign in",
    codeTitle: "Check your inbox.",
    codeBodyLead: "Six digits, sent to ",
    codeBodyTail: ". Enter them to set your new password.",
    codePrimary: "Set new password",
    codeSecondary: "Change email or password",
  },
  verify: {
    title: "Check your inbox.",
    bodyLead: "Six digits, sent to ",
    bodyTail: ".",
    resendIn: "Resend in ",
    resend: "Resend code",
    primary: "Verify",
    secondary: "Use a different email",
  },
  errors: {
    invalidEmail: "That email does not look right.",
    invalidCredentials: "Email or password is incorrect.",
    invalidCode: "That code is wrong or has expired.",
    rateLimited: "Too many attempts. Wait a minute and try again.",
    alertTitle: "Something went wrong",
    network: "Check your connection and try again.",
    generic: "We could not finish that. Try again in a moment.",
    dismiss: "OK",
  },
} as const;
