export const authCopy = {
  step: {
    emailTitle: "What's your email?",
    emailSubtitleSignUp: "Next you'll pick a password, then we'll email you a six-digit code.",
    emailSubtitleSignIn: "Welcome back. Sign in to see your list.",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    continue: "Continue",
    passwordCreateTitle: "Pick a password",
    passwordEnterTitle: "Your password",
    passwordEnterLead: "Signing in as ",
    passwordEnterTail: ".",
    passwordLabel: "Password",
    passwordHint: "At least 8 characters, with one number. We'll email you a code right after.",
    createAccount: "Create account",
    signIn: "Sign in",
    forgot: "Forgot password?",
    haveAccount: "I already have an account",
    newHere: "Create an account",
    show: "Show",
    hide: "Hide",
    back: "Back",
    close: "Close",
  },
  unverified: {
    title: "Email not verified",
    messageLead: "Check your inbox for the six-digit code we sent to ",
    messageTail: ".",
    cancel: "Cancel",
    confirm: "Verify now",
  },
  reset: {
    emailTitle: "Forgot your password?",
    emailSubtitle: "No problem. We'll send a code to confirm it's you.",
    passwordTitle: "Choose a new password",
    passwordLabel: "New password",
    passwordHint: "At least 8 characters, with one number.",
    sendCode: "Send code",
    codeTitle: "Check your inbox",
    codeBodyLead: "Six digits, sent to ",
    codeBodyTail: ". Enter them to set your new password.",
    codePrimary: "Set new password",
    codeSecondary: "Change email or password",
    backToSignIn: "Back to sign in",
  },
  verify: {
    title: "Check your inbox",
    bodyLead: "Six digits, sent to ",
    bodyTail: ".",
    codeLabel: "Code",
    resendIn: "Resend in ",
    resend: "Resend code",
    primary: "Verify",
    secondary: "Use a different email",
  },
  errors: {
    invalidEmail: "That email does not look right.",
    invalidCredentials: "Email or password is incorrect.",
    emailExists: "That email already has an account. Sign in instead.",
    invalidCode: "That code is wrong or has expired.",
    rateLimited: "Too many attempts. Wait a minute and try again.",
    alertTitle: "Something went wrong",
    network: "Check your connection and try again.",
    generic: "We could not finish that. Try again in a moment.",
    dismiss: "OK",
  },
} as const;
