import { allowanceCopy, assistNames } from "@/lib/ai/messages";
import { askMessages } from "@/lib/ask/messages";
import { ASK_TEXT_MAX } from "@/lib/ask/rules";
import type { SpendBucket } from "@/lib/bills/buckets";
import type { PaymentMethod } from "@/lib/ledger/rules";

const plural = (count: number, one: string, many: string = `${one}s`) => `${count} ${count === 1 ? one : many}`;

const places = (groups: readonly string[]) => {
  const [first] = groups;
  return groups.length === 1 && first !== undefined ? first : `${groups.length} groups`;
};

const methodLabel = {
  VENMO: "Venmo",
  CASH: "Cash",
  PAYPAL: "PayPal",
  BANK: "Bank transfer",
  OTHER: "Paid",
} as const satisfies Record<PaymentMethod, string>;

const bucketHint: Partial<Record<SpendBucket, string>> = {
  DRINKS: "Bar tabs might be hiding inside Food.",
  FOOD: "Meals might be sitting under Other.",
  GROCERIES: "Shop runs might be sitting under Other.",
  TRAVEL: "Taxis and fuel might be sitting under Other.",
};

export const askCopy = {
  metaTitle: assistNames.ask,
  back: { home: "Home", group: (name: string) => name },
  title: assistNames.ask,
  body: "Ask about your bills and balances. Bruno answers with the numbers and shows where they came from. It only reads, never changes a thing.",
  you: "You",
  youLower: "you",
  your: "your",
  possessive: (name: string) => `${name}’s`,
  someone: "Someone",
  plural,
  places,
  methodLabel,
  allGroups: "all groups",
  yourGroups: "Your groups",
  scope: { label: "Looking at", all: "All groups", nav: "Groups to ask about" },
  field: {
    label: "Your question",
    placeholder: (example: string) => example,
    placeholderGroup: (group: string) => `Ask about ${group}`,
    placeholderFollow: "Ask a follow-up, like “and last month?”",
    hint: { listening: "Listening. Tap stop when you’re done.", denied: "Mic is off", mic: "Type or tap the mic", type: "Type your question", cost: allowanceCopy.cost },
    count: (length: number, max: number) => `${length} / ${max}`,
    dictate: "Ask out loud",
    micBlocked: "Microphone blocked",
    stop: "Stop",
    stopLabel: "Stop listening",
    listeningEmpty: "Go ahead, Bruno’s listening…",
    ask: "Ask",
    wait: (seconds: number) => `${seconds}s`,
    denied: { title: "Bruno can’t hear you yet.", body: "Allow the microphone in your browser settings, or just type it.", retry: "Try again" },
    over: { title: "That question is too long", body: `Keep it under ${ASK_TEXT_MAX} characters. One thing at a time works best.` },
  },
  thread: { newQuestion: "New question", notSaved: "Nothing here is saved. Leave and it’s gone.", fold: "Fold this answer", open: "Open this answer" },
  suggest: {
    label: "Try asking",
    labelGroup: (group: string) => `Try asking about ${group}`,
    owe: (name: string) => `What do I owe ${name} across all groups?`,
    owed: (name: string) => `What does ${name} owe me?`,
    why: (name: string, amount: string, group: string) => `Why do I owe ${name} ${amount} in ${group}?`,
    whyOwed: (name: string, amount: string, group: string) => `Why does ${name} owe me ${amount} in ${group}?`,
    cost: (group: string) => `What did ${group} cost me?`,
    food: (group: string) => `How much did we spend on food in ${group}?`,
    foodHere: "How much did we spend on food?",
    paid: (name: string) => `Bills ${name} paid this month`,
    changed: (title: string) => `Who changed the ${title} bill?`,
    square: (name: string) => `Am I square with ${name}?`,
    everyone: "Where do I stand with everyone?",
    most: "Who spent the most?",
  },
  thinking: {
    cancel: "Cancel",
    reading: "Reading your question…",
    wrapping: "Putting the answer together…",
    balancePair: (a: string, b: string) => `Checking what ${a} and ${b} owe each other…`,
    balanceOne: (a: string) => `Checking where ${a} stands with everyone…`,
    balanceOneYou: "Checking where you stand with everyone…",
    balanceAll: (group: string | null) => `Adding up balances in ${group ?? "your groups"}…`,
    explain: (b: string, group: string | null) => (group ? `Going through every bill with ${b} in ${group}…` : `Going through every bill with ${b}…`),
    spending: (bucket: string | null, group: string | null) => (bucket ? `Adding up ${bucket} in ${group ?? "your groups"}…` : `Adding up ${group ?? "your groups"}…`),
    bills: (name: string | null) => (name ? `Finding ${name}’s bills…` : "Finding the bills…"),
    find: (title: string | null) => (title ? `Looking for ${title}…` : "Looking for that bill…"),
    history: (title: string | null) => (title ? `Opening ${title}’s history…` : "Checking who did what…"),
  },
  clarify: {
    step: "Quick check",
    stepOf: (index: number, count: number) => `Quick check · ${index} of ${count}`,
    skip: "Skip, Bruno picks the likeliest",
    skipAll: "Skip these, Bruno picks the likeliest",
    person: { title: "Who did you mean?", titleNamed: (name: string) => `Which ${name}?`, sub: (count: number) => `${count} people in your groups match.` },
    group: { title: "Which group?", sub: "More than one of your groups fits." },
    period: { title: "Which month?", sub: "Just this month, or further back?" },
    groupSub: (bills: number, symbol: string) => `${plural(bills, "bill")}, in ${symbol}`,
    periods: { thisMonth: "This month", lastMonth: "Last month", monthBefore: "The month before", all: "All time" },
    allTimeSub: "Everything so far",
  },
  error: {
    title: "Bruno lost the connection",
    body: `Your question’s still in the box. Try again in a moment. ${allowanceCopy.notCounted}`,
    again: "Try again",
    againIn: (seconds: number) => `Try again in ${seconds}s`,
  },
  limit: {
    title: (limit: number) => `That’s today’s ${limit} assists`,
    body: (pro: boolean, proLimit: number) => {
      const base = "These answers stay put until you leave. Bruno’s back at midnight.";
      return pro ? base : `${base} ${allowanceCopy.proSoon(proLimit)}`;
    },
    backHome: "Back to home",
    backGroup: (group: string) => `Back to ${group}`,
  },
  bar: {
    title: assistNames.ask,
    titleGroup: (group: string) => `Ask about ${group}`,
    example: "“Where do I stand with everyone?”",
    exampleWith: (name: string) => `“What do I owe ${name} across all groups?”`,
    exampleGroup: "“What did this cost me?”",
    mic: "Ask out loud",
    resting: `${assistNames.ask} is back at midnight`,
    used: (limit: number) => `Today’s ${limit} assists are used.`,
  },
  money: { even: "Even", allSquare: "All square" },
  notes: {
    currencies: "More than one currency, so Bruno keeps them apart. Nothing gets converted.",
    untagged: (count: number) => `${plural(count, "bill has", "bills have")} untagged items. Those count as Other.`,
    onlyHere: (place: string, rest: string) => `Only in ${place}. Across all your groups, ${rest}.`,
    stillOwes: (name: string, amount: string) => `${name} still owes you ${amount}`,
    stillOwe: (name: string, amount: string) => `you still owe ${name} ${amount}`,
    squareElsewhere: "you’re square everywhere",
  },
  foot: {
    from: (bills: number, payments: number, groups: readonly string[]) =>
      `From ${plural(bills, "bill")}${payments > 0 ? ` and ${plural(payments, "payment")}` : ""} in ${places(groups)}, as of now.`,
    tagged: (bills: number, bucket: string, groups: readonly string[], period: string | null) =>
      `From ${plural(bills, "bill")} tagged ${bucket} in ${places(groups)}${period ? `, ${period}` : ""}.`,
    period: (bills: number, groups: readonly string[], period: string) => `From ${plural(bills, "bill")} in ${places(groups)}, ${period}.`,
    checked: (bills: number, place: string) => `Checked ${plural(bills, "bill")} in ${place}.`,
    history: (title: string, group: string) => `From ${title}’s history in ${group}.`,
    activity: (place: string) => `From the latest activity in ${place}.`,
    free: allowanceCopy.notCounted,
  },
  balance: {
    eyebrow: (name: string) => `Balance with ${name}`,
    eyebrowOthers: (a: string, b: string) => `${a} and ${b}`,
    owesYou: (name: string) => `${name} owes you`,
    youOwe: (name: string) => `You owe ${name}`,
    owes: (a: string, b: string) => `${a} owes ${b}`,
    square: (a: string, b: string) => `${a} and ${b} are`,
    inGroups: (groups: readonly string[]) => `In ${groups.join(" and ")}`,
    settledOn: (day: string) => `Settled up ${day}`,
    noBills: "No bills together yet",
    nothingOwed: "Nothing owed either way",
    addsUp: "How it adds up",
    paidShare: (payer: string, total: string, whose: string, share: string) => `${payer} paid ${total} · ${whose} share ${share}`,
    titles: (titles: readonly string[], more: number) => `${titles.join(" and ")}${more > 0 ? ` and ${more} more` : ""}`,
    together: (bills: number) => `${plural(bills, "bill")} together`,
    paid: (from: string, to: string, amount: string) => `${from} paid ${to} ${amount}`,
    paidSub: (day: string, method: string) => `${day} · ${method}`,
    settle: (amount: string, name: string) => `Settle ${amount} with ${name}`,
    open: (group: string) => `Open ${group}`,
    folded: { owesYou: (name: string, amount: string) => `${name} owes you ${amount}`, youOwe: (name: string, amount: string) => `You owe ${name} ${amount}`, square: (name: string) => `All square with ${name}` },
    followWhyOwe: (name: string, amount: string) => `Why do I owe ${name} ${amount}?`,
    followWhyOwed: (name: string, amount: string) => `Why does ${name} owe me ${amount}?`,
  },
  why: {
    eyebrow: (amount: string, name: string) => `How you got to ${amount} with ${name}`,
    eyebrowSquare: (name: string, group: string) => `You and ${name} in ${group}`,
    eyebrowOthers: (a: string, b: string, group: string) => `${a} and ${b} in ${group}`,
    after: (group: string, bills: number, payments: number) => `In ${group}, after ${plural(bills, "bill")}${payments > 0 ? ` and ${plural(payments, "payment")}` : ""}`,
    head: "Bill by bill, oldest first",
    columnYouOwe: "You owe",
    columnOwes: (name: string) => `${name} owes`,
    columnBalance: "Balance",
    earlier: (count: number) => `${plural(count, "earlier bill or payment", "earlier bills and payments")}`,
    earlierSub: "Running total up to here",
    soYouOwe: (name: string) => `So you owe ${name}`,
    soOwesYou: (name: string) => `So ${name} owes you`,
    soOwes: (a: string, b: string) => `So ${a} owes ${b}`,
    soSquare: "So you’re all square",
  },
  spend: {
    eyebrowShare: (place: string) => `Your share of ${place}`,
    eyebrowTheirs: (name: string, place: string) => `${name}’s share of ${place}`,
    eyebrowGroup: (place: string) => `What ${place} spent`,
    eyebrowBucket: (bucket: string, place: string) => `${bucket} in ${place}`,
    costYou: (place: string) => `${place} cost you`,
    bucketCostYou: (bucket: string, place: string) => `${bucket} in ${place} cost you`,
    cost: (place: string, name: string) => `${place} cost ${name}`,
    bucketCost: (bucket: string, place: string, name: string) => `${bucket} in ${place} cost ${name}`,
    spent: (place: string) => `${place} spent`,
    bucketSpent: (place: string, bucket: string) => `${place} spent on ${bucket}`,
    shareOf: (whose: string, total: string, bills: number) => `${whose} share of ${total} across ${plural(bills, "bill")}`,
    across: (bills: number) => `Across ${plural(bills, "bill")}`,
    yourShare: (share: string, bills: number) => `Your share ${share} · ${plural(bills, "bill")}`,
    biggest: "Biggest bills",
    theBills: "The bills",
    showAll: (count: number) => `Show all ${count}`,
    showFewer: "Show fewer",
    paidShare: (payer: string, whose: string, share: string) => `${payer} paid · ${whose} share ${share}`,
    paidOnly: (payer: string) => `${payer} paid`,
    folded: (caption: string, amount: string) => `${caption} ${amount}`,
    followFood: "Just food?",
    followDrinks: "And drinks?",
    followEverything: "And everything together?",
    followMonth: "And by month?",
    followMost: "Who spent the most?",
    followGroups: "Which group cost me the most?",
  },
  rank: {
    balanceYou: "Where you stand with everyone",
    balanceOther: (name: string) => `Where ${name} stands with everyone`,
    net: (place: string) => `Balances in ${place}`,
    spendPerson: (place: string) => `Who spent what in ${place}`,
    spendGroup: "Your groups, by cost",
    owed: "You’re owed",
    owe: "You owe",
    owedOther: (name: string) => `${name} is owed`,
    oweOther: (name: string) => `${name} owes`,
    people: (count: number) => `Across ${plural(count, "person", "people")}`,
    squareAll: "You and everyone are",
    squareGroup: "Everyone is",
    topOwed: (name: string) => `${name} is owed the most`,
    topSpent: (name: string) => `${name} spent the most`,
    topSpentYou: "You spent the most",
    topGroup: (group: string) => `${group} cost the most`,
    isOwed: "is owed",
    owesRow: "owes",
    bills: (count: number) => plural(count, "bill"),
    together: (count: number) => `${plural(count, "bill")} together`,
    followWith: (name: string) => `What do I owe ${name} across all groups?`,
  },
  list: {
    paid: (name: string) => `Bills ${name} paid`,
    withPerson: (name: string) => `Bills with ${name}`,
    named: (title: string) => `Bills called “${title}”`,
    bucket: (bucket: string) => `${bucket} bills`,
    plain: "Bills",
    inPlace: (text: string, place: string) => `${text} in ${place}`,
    count: (bills: number) => plural(bills, "bill"),
    countIn: (bills: number, currency: string) => `${plural(bills, "bill")} in ${currency}`,
    twoTotals: "More than one currency, so one total each.",
    yourShare: (share: string) => `your share ${share}`,
    notIn: "you weren’t in this one",
    folded: (bills: number, totals: readonly string[]) => `${plural(bills, "bill")} · ${totals.join(" and ")}`,
  },
  activity: {
    eyebrowBill: (title: string, group: string) => `Changes to ${title} · ${group}`,
    eyebrowGroup: (group: string) => `Recent activity in ${group}`,
    eyebrowAll: "Recent activity",
    changed: (who: string, title: string, day: string) => `${who} changed ${title} ${day}`,
    wentFrom: (before: string, after: string) => `Total went from ${before} to ${after}`,
    totalNow: (title: string) => `${title} total`,
    lastTouched: (who: string, day: string) => `Last touched by ${who} ${day}`,
    updates: (count: number) => plural(count, "update"),
    latest: (line: string) => `Latest: ${line}`,
    newest: "Newest first",
    fromTo: (before: string, after: string) => `${before} to ${after}`,
    open: (title: string) => `Open ${title}`,
    folded: (who: string, what: string) => `${who} ${what}`,
  },
  empty: {
    eyebrowSpend: (bucket: string | null, place: string) => `${bucket ?? "Spending"} in ${place}`,
    eyebrowList: (place: string) => `Bills in ${place}`,
    eyebrowActivity: "History",
    eyebrowBalance: (name: string) => `You and ${name}`,
    spendTitle: (bucket: string | null, place: string) => `No ${bucket ?? "spending"} in ${place} yet`,
    spendBucketBody: (checked: number, place: string, bucket: string, hint: string) =>
      `None of the ${plural(checked, "bill")} in ${place} ${checked === 1 ? "is" : "are"} tagged ${bucket}. ${hint}`.trim(),
    spendBody: (checked: number, period: string | null) =>
      checked === 0 ? `There are no bills there${period ? ` ${period}` : ""} yet.` : `Bruno checked ${plural(checked, "bill")}${period ? ` ${period}` : ""} and none of it lands on you.`,
    listTitle: "No bills match",
    listBody: (checked: number, place: string, period: string | null) => `Bruno checked ${plural(checked, "bill")} in ${place}${period ? ` ${period}` : ""}.`,
    activityTitle: (title: string | null) => (title ? `Nothing’s happened to ${title} yet` : "Nothing’s happened here yet"),
    activityBody: "Edits, claims and payments will show up as they happen.",
    balanceTitle: (name: string) => `You and ${name} haven’t shared a bill`,
    balanceBody: (place: string) => `There’s nothing between you in ${place}, so nobody owes anybody.`,
    showFood: "Show food",
    showAll: "Show everything",
    askFood: "Just food?",
    askAll: "And everything together?",
    hints: bucketHint,
    open: (group: string) => `Open ${group}`,
  },
  decline: {
    scope: { eyebrow: "Outside what Bruno knows", title: "That one’s outside Bruno’s lane", body: "Bruno knows your bills, your balances and who changed what. Try one of these instead." },
    private: { eyebrow: "Not one of your groups", title: "Bruno can only see your groups", body: "That group or person isn’t in your account, so its bills stay between its members." },
    change: {
      eyebrow: "Read only",
      title: "Bruno only answers here",
      body: "Ask Bruno never adds, changes or settles anything.",
      bodyPerson: (name: string) => `Ask Bruno never adds, changes or settles anything. Settle up with ${name} where you can check it first.`,
      settle: "Go to Settle up",
      open: (group: string) => `Open ${group}`,
      addBill: "Add a bill",
      ask: (name: string) => `What do I owe ${name}?`,
    },
  },
  toast: { unavailable: askMessages.unavailable },
} as const;
