import { allowanceCopy, assistNames } from "@/lib/ai/messages";
import { askMessages } from "@/lib/ask/messages";
import { ASK_TEXT_MAX } from "@/lib/ask/rules";
import type { SpendBucket } from "@/lib/bills/buckets";
import type { PaymentMethod } from "@/lib/ledger/rules";

const plural = (count: number, one: string, many: string = `${one}s`) => `${count} ${count === 1 ? one : many}`;

const places = (groups: readonly string[]) => {
  const [first] = groups;
  return groups.length === 1 && first !== undefined ? first : `${groups.length} groups`;
};

const methodLabel = {
  VENMO: "Venmo",
  CASH: "Cash",
  PAYPAL: "PayPal",
  BANK: "Bank transfer",
  OTHER: "Paid",
} as const satisfies Record<PaymentMethod, string>;

const bucketHint: Partial<Record<SpendBucket, string>> = {
  DRINKS: "Bar tabs might be hiding inside Food.",
  FOOD: "Meals might be sitting under Other.",
  GROCERIES: "Shop runs might be sitting under Other.",
  TRAVEL: "Taxis and fuel might be sitting under Other.",
};

export const askCopy = {
  metaTitle: assistNames.ask,
  back: { home: "Home", group: (name: string) => name },
  title: assistNames.ask,
  body: "Ask about your bills and balances, or ask Bruno to do something. Bruno shows you exactly what will change, and nothing happens until you tap.",
  you: "You",
  youLower: "you",
  your: "your",
  possessive: (name: string) => `${name}’s`,
  someone: "Someone",
  plural,
  places,
  methodLabel,
  allGroups: "all groups",
  yourGroups: "Your groups",
  scope: { label: "Looking at", all: "All groups", nav: "Groups to ask about" },
  field: {
    label: "Ask or tell Bruno",
    placeholder: (example: string) => example,
    placeholderGroup: (group: string) => `Ask about ${group}`,
    placeholderFollow: "Ask or tell Bruno something else",
    hint: { listening: "Listening. Tap stop when you’re done.", denied: "Mic is off", mic: "Type or tap the mic", type: "Type your question", cost: allowanceCopy.cost },
    count: (length: number, max: number) => `${length} / ${max}`,
    dictate: "Ask out loud",
    micBlocked: "Microphone blocked",
    stop: "Stop",
    stopLabel: "Stop listening",
    listeningEmpty: "Go ahead, Bruno’s listening…",
    ask: "Ask",
    wait: (seconds: number) => `${seconds}s`,
    denied: { title: "Bruno can’t hear you yet.", body: "Allow the microphone in your browser settings, or just type it.", retry: "Try again" },
    over: { title: "That question is too long", body: `Keep it under ${ASK_TEXT_MAX} characters. One thing at a time works best.` },
  },
  thread: { newQuestion: "New question", notSaved: "Nothing here is saved. Leave and it’s gone.", fold: "Fold this answer", open: "Open this answer" },
  suggest: {
    label: "Try asking",
    labelGroup: (group: string) => `Try asking about ${group}`,
    owe: (name: string) => `What do I owe ${name} across all groups?`,
    owed: (name: string) => `What does ${name} owe me?`,
    why: (name: string, amount: string, group: string) => `Why do I owe ${name} ${amount} in ${group}?`,
    whyOwed: (name: string, amount: string, group: string) => `Why does ${name} owe me ${amount} in ${group}?`,
    cost: (group: string) => `What did ${group} cost me?`,
    food: (group: string) => `How much did we spend on food in ${group}?`,
    foodHere: "How much did we spend on food?",
    paid: (name: string) => `Bills ${name} paid this month`,
    changed: (title: string) => `Who changed the ${title} bill?`,
    square: (name: string) => `Am I square with ${name}?`,
    everyone: "Where do I stand with everyone?",
    most: "Who spent the most?",
  },
  thinking: {
    cancel: "Cancel",
    reading: "Reading your question…",
    wrapping: "Putting the answer together…",
    balancePair: (a: string, b: string) => `Checking what ${a} and ${b} owe each other…`,
    balanceOne: (a: string) => `Checking where ${a} stands with everyone…`,
    balanceOneYou: "Checking where you stand with everyone…",
    balanceAll: (group: string | null) => `Adding up balances in ${group ?? "your groups"}…`,
    explain: (b: string, group: string | null) => (group ? `Going through every bill with ${b} in ${group}…` : `Going through every bill with ${b}…`),
    spending: (bucket: string | null, group: string | null) => (bucket ? `Adding up ${bucket} in ${group ?? "your groups"}…` : `Adding up ${group ?? "your groups"}…`),
    bills: (name: string | null) => (name ? `Finding ${name}’s bills…` : "Finding the bills…"),
    find: (title: string | null) => (title ? `Looking for ${title}…` : "Looking for that bill…"),
    history: (title: string | null) => (title ? `Opening ${title}’s history…` : "Checking who did what…"),
  },
  clarify: {
    step: "Quick check",
    stepOf: (index: number, count: number) => `Quick check · ${index} of ${count}`,
    skip: "Skip, Bruno picks the likeliest",
    skipAll: "Skip these, Bruno picks the likeliest",
    person: { title: "Who did you mean?", titleNamed: (name: string) => `Which ${name}?`, sub: (count: number) => `${count} people in your groups match.` },
    group: { title: "Which group?", sub: "More than one of your groups fits." },
    period: { title: "Which month?", sub: "Just this month, or further back?" },
    groupSub: (bills: number, symbol: string) => `${plural(bills, "bill")}, in ${symbol}`,
    periods: { thisMonth: "This month", lastMonth: "Last month", monthBefore: "The month before", all: "All time" },
    allTimeSub: "Everything so far",
  },
  error: {
    title: "Bruno lost the connection",
    body: `Your question’s still in the box. Try again in a moment. ${allowanceCopy.notCounted}`,
    again: "Try again",
    againIn: (seconds: number) => `Try again in ${seconds}s`,
  },
  limit: {
    title: (limit: number) => `That’s today’s ${limit} assists`,
    body: (pro: boolean, proLimit: number) => {
      const base = "These answers stay put until you leave. Bruno’s back at midnight.";
      return pro ? base : `${base} ${allowanceCopy.proSoon(proLimit)}`;
    },
    backHome: "Back to home",
    backGroup: (group: string) => `Back to ${group}`,
  },
  bar: {
    title: assistNames.ask,
    titleGroup: (group: string) => `Ask about ${group}`,
    example: "“Where do I stand with everyone?”",
    exampleWith: (name: string) => `“What do I owe ${name} across all groups?”`,
    exampleGroup: "“What did this cost me?”",
    mic: "Ask out loud",
    resting: `${assistNames.ask} is back at midnight`,
    used: (limit: number) => `Today’s ${limit} assists are used.`,
  },
  money: { even: "Even", allSquare: "All square" },
  notes: {
    currencies: "More than one currency, so Bruno keeps them apart. Nothing gets converted.",
    untagged: (count: number) => `${plural(count, "bill has", "bills have")} untagged items. Those count as Other.`,
    onlyHere: (place: string, rest: string) => `Only in ${place}. Across all your groups, ${rest}.`,
    stillOwes: (name: string, amount: string) => `${name} still owes you ${amount}`,
    stillOwe: (name: string, amount: string) => `you still owe ${name} ${amount}`,
    squareElsewhere: "you’re square everywhere",
  },
  foot: {
    from: (bills: number, payments: number, groups: readonly string[]) =>
      `From ${plural(bills, "bill")}${payments > 0 ? ` and ${plural(payments, "payment")}` : ""} in ${places(groups)}, as of now.`,
    tagged: (bills: number, bucket: string, groups: readonly string[], period: string | null) =>
      `From ${plural(bills, "bill")} tagged ${bucket} in ${places(groups)}${period ? `, ${period}` : ""}.`,
    period: (bills: number, groups: readonly string[], period: string) => `From ${plural(bills, "bill")} in ${places(groups)}, ${period}.`,
    checked: (bills: number, place: string) => `Checked ${plural(bills, "bill")} in ${place}.`,
    history: (title: string, group: string) => `From ${title}’s history in ${group}.`,
    activity: (place: string) => `From the latest activity in ${place}.`,
    free: allowanceCopy.notCounted,
  },
  balance: {
    eyebrow: (name: string) => `Balance with ${name}`,
    eyebrowOthers: (a: string, b: string) => `${a} and ${b}`,
    owesYou: (name: string) => `${name} owes you`,
    youOwe: (name: string) => `You owe ${name}`,
    owes: (a: string, b: string) => `${a} owes ${b}`,
    square: (a: string, b: string) => `${a} and ${b} are`,
    inGroups: (groups: readonly string[]) => `In ${groups.join(" and ")}`,
    settledOn: (day: string) => `Settled up ${day}`,
    noBills: "No bills together yet",
    nothingOwed: "Nothing owed either way",
    addsUp: "How it adds up",
    paidShare: (payer: string, total: string, whose: string, share: string) => `${payer} paid ${total} · ${whose} share ${share}`,
    titles: (titles: readonly string[], more: number) => `${titles.join(" and ")}${more > 0 ? ` and ${more} more` : ""}`,
    together: (bills: number) => `${plural(bills, "bill")} together`,
    paid: (from: string, to: string, amount: string) => `${from} paid ${to} ${amount}`,
    paidSub: (day: string, method: string) => `${day} · ${method}`,
    settle: (amount: string, name: string) => `Settle ${amount} with ${name}`,
    open: (group: string) => `Open ${group}`,
    folded: { owesYou: (name: string, amount: string) => `${name} owes you ${amount}`, youOwe: (name: string, amount: string) => `You owe ${name} ${amount}`, square: (name: string) => `All square with ${name}` },
    followWhyOwe: (name: string, amount: string) => `Why do I owe ${name} ${amount}?`,
    followWhyOwed: (name: string, amount: string) => `Why does ${name} owe me ${amount}?`,
  },
  why: {
    eyebrow: (amount: string, name: string) => `How you got to ${amount} with ${name}`,
    eyebrowSquare: (name: string, group: string) => `You and ${name} in ${group}`,
    eyebrowOthers: (a: string, b: string, group: string) => `${a} and ${b} in ${group}`,
    after: (group: string, bills: number, payments: number) => `In ${group}, after ${plural(bills, "bill")}${payments > 0 ? ` and ${plural(payments, "payment")}` : ""}`,
    head: "Bill by bill, oldest first",
    columnYouOwe: "You owe",
    columnOwes: (name: string) => `${name} owes`,
    columnBalance: "Balance",
    earlier: (count: number) => `${plural(count, "earlier bill or payment", "earlier bills and payments")}`,
    earlierSub: "Running total up to here",
    soYouOwe: (name: string) => `So you owe ${name}`,
    soOwesYou: (name: string) => `So ${name} owes you`,
    soOwes: (a: string, b: string) => `So ${a} owes ${b}`,
    soSquare: "So you’re all square",
  },
  spend: {
    eyebrowShare: (place: string) => `Your share of ${place}`,
    eyebrowTheirs: (name: string, place: string) => `${name}’s share of ${place}`,
    eyebrowGroup: (place: string) => `What ${place} spent`,
    eyebrowBucket: (bucket: string, place: string) => `${bucket} in ${place}`,
    costYou: (place: string) => `${place} cost you`,
    bucketCostYou: (bucket: string, place: string) => `${bucket} in ${place} cost you`,
    cost: (place: string, name: string) => `${place} cost ${name}`,
    bucketCost: (bucket: string, place: string, name: string) => `${bucket} in ${place} cost ${name}`,
    spent: (place: string) => `${place} spent`,
    bucketSpent: (place: string, bucket: string) => `${place} spent on ${bucket}`,
    shareOf: (whose: string, total: string, bills: number) => `${whose} share of ${total} across ${plural(bills, "bill")}`,
    across: (bills: number) => `Across ${plural(bills, "bill")}`,
    yourShare: (share: string, bills: number) => `Your share ${share} · ${plural(bills, "bill")}`,
    biggest: "Biggest bills",
    theBills: "The bills",
    showAll: (count: number) => `Show all ${count}`,
    showFewer: "Show fewer",
    paidShare: (payer: string, whose: string, share: string) => `${payer} paid · ${whose} share ${share}`,
    paidOnly: (payer: string) => `${payer} paid`,
    folded: (caption: string, amount: string) => `${caption} ${amount}`,
    followFood: "Just food?",
    followDrinks: "And drinks?",
    followEverything: "And everything together?",
    followMonth: "And by month?",
    followMost: "Who spent the most?",
    followGroups: "Which group cost me the most?",
  },
  rank: {
    balanceYou: "Where you stand with everyone",
    balanceOther: (name: string) => `Where ${name} stands with everyone`,
    net: (place: string) => `Balances in ${place}`,
    spendPerson: (place: string) => `Who spent what in ${place}`,
    spendGroup: "Your groups, by cost",
    owed: "You’re owed",
    owe: "You owe",
    owedOther: (name: string) => `${name} is owed`,
    oweOther: (name: string) => `${name} owes`,
    people: (count: number) => `Across ${plural(count, "person", "people")}`,
    squareAll: "You and everyone are",
    squareGroup: "Everyone is",
    topOwed: (name: string) => `${name} is owed the most`,
    topSpent: (name: string) => `${name} spent the most`,
    topSpentYou: "You spent the most",
    topGroup: (group: string) => `${group} cost the most`,
    isOwed: "is owed",
    owesRow: "owes",
    bills: (count: number) => plural(count, "bill"),
    together: (count: number) => `${plural(count, "bill")} together`,
    followWith: (name: string) => `What do I owe ${name} across all groups?`,
  },
  list: {
    paid: (name: string) => `Bills ${name} paid`,
    withPerson: (name: string) => `Bills with ${name}`,
    named: (title: string) => `Bills called “${title}”`,
    bucket: (bucket: string) => `${bucket} bills`,
    plain: "Bills",
    inPlace: (text: string, place: string) => `${text} in ${place}`,
    count: (bills: number) => plural(bills, "bill"),
    countIn: (bills: number, currency: string) => `${plural(bills, "bill")} in ${currency}`,
    twoTotals: "More than one currency, so one total each.",
    yourShare: (share: string) => `your share ${share}`,
    notIn: "you weren’t in this one",
    folded: (bills: number, totals: readonly string[]) => `${plural(bills, "bill")} · ${totals.join(" and ")}`,
  },
  activity: {
    eyebrowBill: (title: string, group: string) => `Changes to ${title} · ${group}`,
    eyebrowGroup: (group: string) => `Recent activity in ${group}`,
    eyebrowAll: "Recent activity",
    changed: (who: string, title: string, day: string) => `${who} changed ${title} ${day}`,
    wentFrom: (before: string, after: string) => `Total went from ${before} to ${after}`,
    totalNow: (title: string) => `${title} total`,
    lastTouched: (who: string, day: string) => `Last touched by ${who} ${day}`,
    updates: (count: number) => plural(count, "update"),
    latest: (line: string) => `Latest: ${line}`,
    newest: "Newest first",
    fromTo: (before: string, after: string) => `${before} to ${after}`,
    open: (title: string) => `Open ${title}`,
    folded: (who: string, what: string) => `${who} ${what}`,
  },
  empty: {
    eyebrowSpend: (bucket: string | null, place: string) => `${bucket ?? "Spending"} in ${place}`,
    eyebrowList: (place: string) => `Bills in ${place}`,
    eyebrowActivity: "History",
    eyebrowBalance: (name: string) => `You and ${name}`,
    spendTitle: (bucket: string | null, place: string) => `No ${bucket ?? "spending"} in ${place} yet`,
    spendBucketBody: (checked: number, place: string, bucket: string, hint: string) =>
      `None of the ${plural(checked, "bill")} in ${place} ${checked === 1 ? "is" : "are"} tagged ${bucket}. ${hint}`.trim(),
    spendBody: (checked: number, period: string | null) =>
      checked === 0 ? `There are no bills there${period ? ` ${period}` : ""} yet.` : `Bruno checked ${plural(checked, "bill")}${period ? ` ${period}` : ""} and none of it lands on you.`,
    listTitle: "No bills match",
    listBody: (checked: number, place: string, period: string | null) => `Bruno checked ${plural(checked, "bill")} in ${place}${period ? ` ${period}` : ""}.`,
    activityTitle: (title: string | null) => (title ? `Nothing’s happened to ${title} yet` : "Nothing’s happened here yet"),
    activityBody: "Edits, claims and payments will show up as they happen.",
    balanceTitle: (name: string) => `You and ${name} haven’t shared a bill`,
    balanceBody: (place: string) => `There’s nothing between you in ${place}, so nobody owes anybody.`,
    showFood: "Show food",
    showAll: "Show everything",
    askFood: "Just food?",
    askAll: "And everything together?",
    hints: bucketHint,
    open: (group: string) => `Open ${group}`,
  },
  decline: {
    scope: { eyebrow: "Outside what Bruno knows", title: "That one’s outside Bruno’s lane", body: "Bruno knows your bills, your balances and who changed what. Try one of these instead." },
    private: { eyebrow: "Not one of your groups", title: "Bruno can only see your groups", body: "That group or person isn’t in your account, so its bills stay between its members." },
    change: {
      eyebrow: "Not here",
      title: "Bruno can’t do that one here",
      body: "Bruno can send reminders, record and confirm payments, and change, close or delete a bill. For anything else, open the group.",
      bodyPerson: (name: string) => `Bruno can’t do that one here. You can settle up with ${name} yourself.`,
      settle: "Go to Settle up",
      open: (group: string) => `Open ${group}`,
      addBill: "Add a bill",
      ask: (name: string) => `What do I owe ${name}?`,
    },
  },
  toast: { unavailable: askMessages.unavailable },
  act: {
    suggestLabel: "Or ask Bruno to",
    confirmFirst: "You confirm first",
    suggest: {
      remindAll: "Remind everyone who owes me",
      settle: (name: string) => `Settle up with ${name}`,
      split: (title: string) => `Make ${title} an equal split`,
    },
    follow: { settle: (amount: string, name: string) => `Settle ${amount} with ${name}`, remind: (name: string) => `Remind ${name}` },
    notNow: "Not now",
    refresh: "Refresh",
    tryAgain: "Try again",
    undo: "Undo",
    fold: "Fold",
    amountLabel: "Amount",
    amountHint: "Tap the amount to change it",
    before: "Before",
    after: "After",
    share: "Share",
    group: "Group",
    paidBy: "Paid by",
    name: "Name",
    date: "Date",
    total: "Total",
    afterThis: "After this",
    ifConfirm: "If you confirm",
    method: "How",
    stillUnclaimed: "Still unclaimed",
    even: "Even",
    people: (count: number) => plural(count, "person", "people"),
    ways: (count: number) => `${count} ways`,
    list: (names: readonly string[]) => (names.length > 1 ? `${names.slice(0, -1).join(", ")} and ${names[names.length - 1] ?? ""}` : (names[0] ?? "")),
    bill: {
      paid: (payer: string) => `${payer} paid`,
      claimed: (claimed: number, people: number) => `${claimed} of ${people} have claimed`,
      byItems: "split by items",
      ways: (count: number) => (count === 1 ? "all on one person" : `split ${count} ways`),
      open: "Open bill",
      openNamed: (title: string) => `Open ${title}`,
      editor: "Open the editor",
    },
    foot: {
      ready: "Uses 1 assist when you confirm. Not now is free.",
      last: "Uses your last assist today when you confirm. Not now is free.",
      working: "Uses 1 assist once it’s done.",
      free: allowanceCopy.notCounted,
      stale: "Nothing was changed. Refreshing is free.",
      none: "No assists left today. Bruno can still answer what you’ve asked.",
      used: (left: number, limit: number, undo: boolean) => `Used 1 assist · ${allowanceCopy.leftShort(left, limit)}${undo ? ". Undo is free." : ""}`,
    },
    line: { notNow: "Not now.", unchanged: "Nothing was changed.", undone: "Undone.", free: "No assist used" },
    alert: {
      failed: { title: "Bruno couldn’t do that", body: "Something went wrong before anything was saved. Nothing was changed, and it didn’t use an assist." },
      stale: { title: "This changed while you were deciding", body: (place: string) => `Something in ${place} changed since Bruno prepared this. Refresh to see the new numbers.` },
      limit: {
        title: (limit: number) => `That’s your ${limit} assists for today`,
        body: (pro: boolean, proLimit: number) => `Bruno can’t make changes until midnight. You can still do this yourself.${pro ? "" : ` ${allowanceCopy.proSoon(proLimit)}`}`,
      },
    },
    remindDebts: {
      eyebrow: "Send reminders",
      title: "Remind everyone who owes you",
      titleOne: (name: string) => `Remind ${name} to pay you back`,
      sub: "Each person gets a short email from Bruno with what they owe and a link to settle up.",
      recent: (sent: string, again: string) => `Reminded ${sent}. Again ${again}.`,
      off: "Turned off reminder emails",
      noEmail: "No email on file",
      total: "Asking for",
      primary: (count: number) => (count === 0 ? "Pick someone to remind" : `Send ${plural(count, "reminder")}`),
      working: (count: number) => `Sending ${plural(count, "reminder")}…`,
      done: (count: number) => `Sent ${plural(count, "reminder")}.`,
      doneSub: (names: string) => `${names} will get an email in a minute.`,
      folded: (count: number) => `Sent ${plural(count, "reminder")}`,
      link: (group: string) => `Open ${group}`,
      linkAll: "See your groups",
    },
    remindClaims: {
      eyebrow: "Remind people to claim",
      title: (count: number, title: string) => `Nudge ${plural(count, "person", "people")} to claim on ${title}`,
      sub: "They get an email with a link straight to the bill.",
      waiting: "Nothing claimed yet",
      off: "Turned off bill emails",
      noEmail: "No email on file",
      total: "Still unclaimed",
      primary: (count: number) => (count === 0 ? "Nobody can be emailed" : `Nudge ${plural(count, "person", "people")}`),
      working: (count: number) => `Nudging ${plural(count, "person", "people")}…`,
      done: (names: string, title: string) => `Nudged ${names} on ${title}.`,
      doneSub: "You’ll see their claims land on the bill.",
      folded: (count: number, title: string) => `Nudged ${plural(count, "person", "people")} on ${title}`,
    },
    pay: {
      eyebrow: "Record a payment",
      titlePaid: (name: string) => `Record that you paid ${name}`,
      titleReceived: (name: string) => `Record that ${name} paid you`,
      linePaid: (name: string) => `You paid ${name}`,
      lineReceived: (name: string) => `${name} paid you`,
      metaPaid: (name: string, amount: string, group: string) => `You owe ${name} ${amount} in ${group}`,
      metaReceived: (name: string, amount: string, group: string) => `${name} owes you ${amount} in ${group}`,
      partial: (left: string) => `Partial · ${left} left`,
      over: (max: string) => `The most is ${max}`,
      square: (name: string, group: string) => `You and ${name} are square in ${group}`,
      stillOwe: (name: string, amount: string) => `You’ll still owe ${name} ${amount}`,
      stillOwed: (name: string, amount: string) => `${name} will still owe you ${amount}`,
      youOwe: (name: string, amount: string) => `You’ll owe ${name} ${amount}`,
      noteConfirm: (name: string) => `${name} gets a note to confirm it. Your balance updates once ${name} does.`,
      noteGuest: "Counts straight away.",
      noteReceived: (name: string) => `Counts straight away, since it’s money you got. ${name} gets a note that you recorded it.`,
      primaryPaid: (amount: string) => `Record ${amount}`,
      primaryReceived: (amount: string, name: string) => `Record ${amount} from ${name}`,
      enter: "Enter an amount",
      working: (amount: string) => `Recording ${amount}…`,
      donePaid: (amount: string, name: string) => `Recorded ${amount} to ${name}.`,
      doneReceived: (amount: string, name: string) => `Recorded ${amount} from ${name}.`,
      donePending: (name: string, group: string) => `Waiting for ${name} to confirm. It shows as pending in ${group} until then.`,
      undonePaid: (amount: string, name: string) => `The ${amount} payment to ${name} was removed.`,
      undoneReceived: (amount: string, name: string) => `The ${amount} payment from ${name} was removed.`,
      foldedPaid: (amount: string, name: string, pending: boolean) => `Recorded ${amount} to ${name}${pending ? ` · waiting for ${name}` : ""}`,
      foldedReceived: (amount: string, name: string) => `Recorded ${amount} from ${name}`,
      link: "View payment",
    },
    pending: {
      eyebrow: "Confirm a payment",
      title: (name: string, amount: string) => `${name} says they paid you ${amount}`,
      sub: (name: string, when: string, method: string | null) => `${name} recorded it ${when}${method ? `, by ${method}` : ""}. Check it arrived before you confirm.`,
      note: (name: string) => `If it didn’t arrive, decline it. ${name} gets a note to check, and nothing moves.`,
      primary: (amount: string) => `Confirm ${amount}`,
      decline: "Decline",
      working: (amount: string) => `Confirming ${amount}…`,
      declining: "Declining…",
      done: (amount: string, name: string) => `Confirmed ${amount} from ${name}.`,
      declined: (name: string, amount: string) => `Declined ${name}’s ${amount}.`,
      declinedSub: (name: string) => `${name} gets a note to check it. Nothing moved.`,
      foldedDeclined: (name: string, amount: string) => `Declined ${name}’s ${amount}`,
      folded: (amount: string, name: string) => `Confirmed ${amount} from ${name}`,
    },
    change: {
      eyebrow: "Change a bill",
      seen: "Everyone on the bill will see it in Activity.",
      splitTitle: (title: string) => `Split ${title} equally`,
      splitSub: (count: number, each: string) => `${plural(count, "person", "people")}, ${each} each.`,
      splitCloses: "Claiming closes, and anyone who hasn’t claimed gets a share.",
      splitPrimary: (total: string, count: number) => `Split ${total} ${count} ways`,
      splitWorking: "Changing the split…",
      splitDone: (title: string) => `${title} is now split equally.`,
      splitDoneSub: (each: string, closes: boolean) => `${each} each.${closes ? " Claiming is closed." : ""}`,
      splitFolded: (title: string, each: string) => `Split ${title} equally · ${each} each`,
      payerTitle: (name: string, title: string) => `Make ${name} the payer of ${title}`,
      payerNote: "Shares stay the same. Only who they’re owed to changes.",
      payerMove: (name: string, group: string) => `You and ${name} in ${group}`,
      owesYou: (name: string, amount: string) => `${name} owes you ${amount}`,
      youOwe: (amount: string) => `You owe ${amount}`,
      payerPrimary: (name: string, total: string) => `Make ${name} payer of ${total}`,
      payerWorking: "Changing the payer…",
      payerDone: (name: string, title: string) => `${name} is now the payer on ${title}.`,
      payerFolded: (name: string, title: string) => `${name} is the payer on ${title}`,
      renameTitle: (title: string) => `Rename ${title}`,
      renameNote: "Amounts and shares stay exactly as they are.",
      renamePrimary: "Rename 1 bill",
      renameWorking: "Renaming…",
      renameDone: (title: string) => `Renamed to ${title}.`,
      renameDoneSub: "Nothing else changed.",
      renameFolded: (title: string) => `Renamed to ${title}`,
      dateTitle: (title: string, day: string) => `Move ${title} to ${day}`,
      datePrimary: "Move 1 bill",
      dateWorking: "Moving…",
      dateDone: (day: string) => `Moved to ${day}.`,
      dateFolded: (title: string, day: string) => `Moved ${title} to ${day}`,
      totalTitle: (title: string, total: string) => `Change ${title} to ${total}`,
      totalPrimary: (total: string) => `Change total to ${total}`,
      totalWorking: "Changing the total…",
      totalDone: (title: string, total: string) => `${title} is now ${total}.`,
      totalFolded: (title: string, total: string) => `${title} is now ${total}`,
    },
    close: {
      eyebrow: "Finish claiming",
      title: (title: string) => `Close claiming on ${title}`,
      sub: (amount: string) => `${amount} is still unclaimed. Bruno shares it equally between everyone on the bill.`,
      subNone: "Everything is claimed.",
      note: "Nobody can claim more after this. Everyone gets an email with their final share.",
      primary: (amount: string) => `Close and share ${amount}`,
      primaryNone: "Close claiming",
      working: "Closing the bill…",
      done: (title: string) => `Closed ${title}.`,
      doneSub: "The leftovers were shared out.",
      doneSubNone: "Everyone’s share is final.",
      folded: (title: string) => `Closed ${title}`,
    },
    remove: {
      eyebrow: "Delete a bill",
      title: (title: string) => `Delete ${title}?`,
      sub: (group: string) => `It goes for everyone in ${group}, and it can’t be undone.`,
      owesLess: (name: string, amount: string) => `${name} owes you ${amount} less`,
      oweLess: (name: string, amount: string) => `you owe ${name} ${amount} less`,
      more: (count: number) => plural(count, "more change"),
      none: "No balances change",
      primary: "Delete bill",
      working: "Deleting…",
      done: (title: string) => `Deleted ${title}.`,
      doneSubNone: "Nothing else changed.",
      folded: (title: string) => `Deleted ${title}`,
      link: (group: string) => `Open ${group}`,
    },
    denied: {
      bill: (name: string) => `Only ${name} or a group admin can do this`,
      billBody: (name: string) => `${name} added this bill, so changes come from ${name} or an admin.`,
      billTitle: {
        remindClaims: (title: string) => `Nudge people on ${title}`,
        splitEvenly: (title: string) => `Split ${title} equally`,
        changePayer: (title: string) => `Change who paid for ${title}`,
        renameBill: (title: string) => `Rename ${title}`,
        changeDate: (title: string) => `Move ${title}`,
        changeTotal: (title: string) => `Change ${title}`,
        finishClaiming: (title: string) => `Close claiming on ${title}`,
        deleteBill: (title: string) => `Delete ${title}`,
      },
      payTitle: (from: string, to: string, amount: string | null) => `Record that ${from} paid ${to}${amount ? ` ${amount}` : ""}`,
      payLine: (from: string, to: string) => `${from} paid ${to}`,
      pay: (a: string, b: string) => `Only ${a} or ${b} can record this`,
      payBody: "It’s a payment between the two of them, so it has to come from one of them. You’ll see it in the group once they do.",
      openGroup: (group: string) => `Open ${group}`,
      home: "Back to home",
    },
    note: {
      eyebrowNothing: "Nothing to do",
      eyebrowHandoff: "Adding a bill",
      eyebrowUnsupported: "Not here",
      handoffTitle: `New bills go through ${assistNames.say}`,
      handoffBody: `${assistNames.say} reads the bill back and checks who’s in it before anything is saved. Bruno will bring your words over.`,
      handoffOpen: `Open ${assistNames.say} with this`,
      handoffBodyPick: `${assistNames.say} reads the bill back and checks who’s in it before anything is saved. Pick the group first, then say it there.`,
      handoffPick: "Add a bill",
      square: (name: string) => `You and ${name} are already square`,
      squareBody: (group: string | null) => (group ? `Nothing to settle in ${group}.` : "Nothing to settle between you."),
      awaiting: (name: string) => `Waiting on ${name}`,
      awaitingBody: (amount: string, name: string, group: string) => `You already recorded ${amount} to ${name} in ${group}. It counts once ${name} confirms.`,
      theyOwe: (name: string) => `${name} owes you, not the other way`,
      theyOweBody: (group: string, name: string, amount: string) => `In ${group}, ${name} owes you ${amount}. Ask Bruno to record that ${name} paid you instead.`,
      youOwe: (name: string) => `You owe ${name}, not the other way`,
      youOweBody: (group: string, name: string, amount: string) => `In ${group}, you owe ${name} ${amount}. Ask Bruno to record that you paid ${name} instead.`,
      nobodyOwes: "Nobody owes you right now",
      nobodyOwesOne: (name: string) => `${name} doesn’t owe you anything`,
      nobodyOwesBody: "There’s nobody to remind.",
      noPending: "No payments are waiting for you",
      noPendingOne: (name: string) => `${name} hasn’t recorded a payment to you`,
      noPendingBody: "When someone records a payment to you, you can confirm it here.",
      allClaimed: (title: string) => `Everyone has claimed on ${title}`,
      allClaimedBody: "There’s nobody left to nudge.",
      noChange: (title: string) => `${title} is already like that`,
      noChangeBody: "There’s nothing to change.",
      unsupported: {
        generic: {
          title: "Bruno can’t do that one here",
          body: "Bruno can send reminders, record and confirm payments, and rename, re-split, move, close or delete a bill. For anything else, open the group.",
        },
        simpleBill: { title: "That change needs the full editor", body: "This bill has more than one item, tax, a tip or exact amounts, so Bruno can’t change it in one step." },
        notClaiming: { title: "That bill isn’t open for claiming", body: "Its shares are already final." },
        billGone: { title: "Bruno couldn’t find that bill", body: "It may have been deleted, or it’s in a group you’re not in." },
        needsBill: { title: "Which bill?", body: "Bruno couldn’t find a bill with that name. Try its exact name." },
        needsPerson: { title: "Who do you mean?", body: "Bruno couldn’t find that person in your groups." },
        badDate: { title: "That date doesn’t work", body: "Bills can’t be dated in the future, or more than two years back." },
      },
    },
    clarify: {
      bill: { title: "Which bill?", sub: (count: number) => `${plural(count, "bill")} match.` },
      billSub: (group: string, day: string, total: string) => `${group} · ${day} · ${total}`,
      amount: { title: "How much?", subPaid: (name: string, amount: string, group: string) => `You owe ${name} ${amount} in ${group}.`, subReceived: (name: string, amount: string, group: string) => `${name} owes you ${amount} in ${group}.` },
      all: "All of it",
      half: "Half",
      other: "Another amount",
      otherSub: "Type it in",
      payment: { title: "Which payment?", sub: (count: number) => `${plural(count, "payment is", "payments are")} waiting for you.` },
      paymentLabel: (name: string, amount: string) => `${name} · ${amount}`,
      paymentSub: (group: string, day: string) => `${group} · ${day}`,
    },
  },
} as const;
