import type { SFSymbol } from "sf-symbols-typescript";

import type { Theme, ThemeName } from "./types";

export const themes = {
  light: {
    canvas: "#FFFFFF",
    surface: "#F2F2F2",
    surface2: "#E6E6E6",
    border: "#E0E0E0",
    ink: "#000000",
    ink2: "#3D3D3D",
    ink3: "#6E6E6E",
    ink4: "#A8A8A8",
    onInk: "#FFFFFF",
    accent: "#9FE870",
    onAccent: "#000000",
    bar: "#000000",
    barMuted: "#D9D9D9",
  },
  dark: {
    canvas: "#000000",
    surface: "#1A1A1A",
    surface2: "#262626",
    border: "#2E2E2E",
    ink: "#FFFFFF",
    ink2: "#C9C9C9",
    ink3: "#8F8F8F",
    ink4: "#5A5A5A",
    onInk: "#000000",
    accent: "#A6FF7A",
    onAccent: "#000000",
    bar: "#FFFFFF",
    barMuted: "#3A3A3A",
  },
} as const satisfies Record<ThemeName, Theme>;

export const fonts = {
  sans: "System",
  mono: "Menlo",
  displayMedium: "BricolageGrotesque-Medium",
  displayBold: "BricolageGrotesque-Bold",
  displayHeavy: "BricolageGrotesque-ExtraBold",
} as const;

export const weights = {
  regular: "400",
  medium: "500",
  semibold: "600",
  bold: "700",
  heavy: "800",
} as const;

export const type = {
  money: {
    fontFamily: fonts.displayHeavy,
    fontWeight: weights.heavy,
    fontSize: 64,
    lineHeight: 68,
    letterSpacing: -2,
  },
  display: {
    fontFamily: fonts.displayHeavy,
    fontWeight: weights.heavy,
    fontSize: 44,
    lineHeight: 48,
    letterSpacing: -1.2,
  },
  title: {
    fontFamily: fonts.displayBold,
    fontWeight: weights.bold,
    fontSize: 32,
    lineHeight: 36,
    letterSpacing: -0.6,
  },
  heading: {
    fontFamily: fonts.displayBold,
    fontWeight: weights.bold,
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: -0.3,
  },
  body: {
    fontFamily: fonts.sans,
    fontWeight: weights.regular,
    fontSize: 17,
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodyMedium: {
    fontFamily: fonts.sans,
    fontWeight: weights.medium,
    fontSize: 17,
    lineHeight: 24,
    letterSpacing: 0,
  },
  caption: {
    fontFamily: fonts.sans,
    fontWeight: weights.regular,
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: 0,
  },
  captionStrong: {
    fontFamily: fonts.sans,
    fontWeight: weights.semibold,
    fontSize: 15,
    lineHeight: 20,
    letterSpacing: 0,
  },
  label: {
    fontFamily: fonts.sans,
    fontWeight: weights.medium,
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0,
  },
  num: {
    fontFamily: fonts.sans,
    fontWeight: weights.medium,
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: 0,
  },
  numLarge: {
    fontFamily: fonts.sans,
    fontWeight: weights.semibold,
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: 0,
  },
  code: {
    fontFamily: fonts.displayBold,
    fontWeight: weights.bold,
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: 0,
  },
  note: {
    fontFamily: fonts.mono,
    fontWeight: weights.regular,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
  },
} as const;

export const displayTypeTokens = [
  "money",
  "display",
  "title",
  "heading",
  "code",
] as const;

export const space = {
  s4: 4,
  s8: 8,
  s12: 12,
  s16: 16,
  s20: 20,
  s24: 24,
  s32: 32,
  s40: 40,
  s48: 48,
  s64: 64,
} as const;

export const radius = {
  pill: 999,
  tile: 20,
  field: 12,
  compact: 8,
} as const;

export const layout = {
  margin: 20,
  top: 64,
  topInset: 16,
  bottom: 24,
  hairline: 1,
  hit: 44,
  disabledOpacity: 0.5,
  nav: { height: 44, side: 12, symbol: 17, circle: 44 },
  button: { fillWidth: 10000 },
  pill: { height: 56, heightSmall: 40, paddingHorizontal: 20, gap: 12 },
  field: {
    height: 56,
    paddingHorizontal: 16,
    border: 1.5,
    focus: 2,
    labelGap: 8,
    hintGap: 6,
    prefixGap: 6,
    suffixGap: 12,
    multilinePaddingVertical: 14,
    multilineLines: { min: 3 },
  },
  row: {
    minHeight: 64,
    logoMinHeight: 68,
    paddingVertical: 10,
    gap: 14,
    subGap: 2,
    chevron: 14,
    chevronGap: 8,
  },
  icon: { row: 24 },
  logo: {
    row: 44,
    detail: 56,
    tiny: 24,
    request: { small: 128, large: 256 },
    letterScale: 0.45,
  },
  tile: { padding: 20, gap: 12, minHeight: 120, logoGap: 8 },
  chip: { height: 28, paddingHorizontal: 10, gap: 6 },
  chart: {
    height: 120,
    column: 68,
    barWidth: 18,
    corner: 4,
    stub: 4,
    labelGap: 12,
    pillHeight: 28,
    pillPadding: 10,
    amountGap: 6,
  },
  bar: { height: 8, trackRadius: 4, rowGap: 8, rowHeight: 64, rowSpacing: 20 },
  code: { cell: 56, gap: 8, radius: 12, border: 1.5, focus: 2, caretWidth: 2, caretHeight: 26 },
  tabs: { height: 36 },
  toggle: { width: 51, height: 31 },
  stat: { rowHeight: 52 },
  onboarding: { markTop: 24, mark: 40 },
  tabBar: { height: 62, bottom: 26 },
  emptyState: { gap: 8, actionGap: 20, maxWidth: 300 },
  money: { captionGap: 8, minimumScale: 0.7 },
  disclosure: { height: 44, gap: 6 },
  loading: { bar: 12, long: 0.6, short: 0.35, rows: 4, gap: 8, hero: 48 },
  link: { height: 44 },
  select: { chevron: 12, gap: 6 },
  suggestions: { max: 5 },
  nativeAlert: { host: 1 },
} as const;

export const motion = {
  duration: { fade: 120, enter: 260, count: 600, pulse: 900, inputSync: 120 },
  spring: { damping: 20, stiffness: 220, mass: 1 },
  pressedOpacity: 0.6,
  stagger: 30,
  staggerMax: 6,
  enterOffset: 8,
} as const;

export const icons = {
  tabOverview: "house",
  tabOverviewSelected: "house.fill",
  tabSubscriptions: "creditcard",
  tabSubscriptionsSelected: "creditcard.fill",
  tabInsights: "chart.bar",
  tabInsightsSelected: "chart.bar.fill",
  tabSettings: "gearshape",
  tabSettingsSelected: "gearshape.fill",
  back: "chevron.left",
  close: "xmark",
  add: "plus",
  chevron: "chevron.right",
  select: "chevron.up.chevron.down",
  disclose: "chevron.down",
  collapse: "chevron.up",
  check: "checkmark",
  sort: "arrow.up.arrow.down",
  search: "magnifyingglass",
  retry: "arrow.clockwise",
  remove: "xmark.circle.fill",
  calendar: "calendar",
  repeat: "arrow.trianglehead.2.clockwise",
  tag: "tag",
  card: "creditcard",
  note: "note.text",
  clock: "clock",
  pause: "pause",
  cancel: "xmark.circle",
  trash: "trash",
  bell: "bell",
  mail: "envelope",
  appearance: "paintpalette",
  currency: "globe",
  person: "person",
  signOut: "rectangle.portrait.and.arrow.right",
  trial: "gift",
} as const satisfies Record<string, SFSymbol>;

export const iconSizes = { bar: 22, inline: 16, tight: 14 } as const;

export const symbolWeight = "regular" as const;

export const logoSizes = ["row", "detail", "tiny"] as const;
